In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.metrics import classification_report
from sklearn.svm import OneClassSVM
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

dataset=pd.read_csv(r"C:\e\学习资料\02-03\data\data_process\integration_a.csv")
print (dataset.value_counts('Label'))

C:\d\anaconda\envs\tensorflow\lib\site-packages\IPython\core\interactiveshell.py:3072: DtypeWarning: Columns (80,81,83) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


Label
Benign                      190596
DoS attacks-Hulk            161669
DDOS attack-HOIC            123482
FTP-BruteForce               96680
SSH-Bruteforce               93794
DDoS attacks-LOIC-HTTP       86428
Infilteration                80968
Bot                          71548
DoS attacks-SlowHTTPTest     48962
DoS attacks-GoldenEye        33206
DoS attacks-Slowloris         8792
DDOS attack-LOIC-UDP          1730
Brute Force -Web               362
Brute Force -XSS               151
SQL Injection                   53
dtype: int64


In [2]:
dataset.drop('Flow ID',axis=1,inplace=True)
dataset.drop('Src IP',axis=1,inplace=True)
dataset.drop('Src Port',axis=1,inplace=True)
dataset.drop('Dst IP',axis=1,inplace=True)
print ( dataset.shape)

(998421, 80)


In [3]:
dt1=dataset.groupby('Label').apply(pd.DataFrame.sample, frac=0.5).reset_index(level='Label', drop=True)
dt2=dataset.drop(dt1.index)
print (dt1.shape)
print  ( dt2.shape)

(499210, 80)
(499211, 80)


In [4]:
s1=dt1.groupby('Label').apply(pd.DataFrame.sample, frac=0.5).reset_index(level='Label', drop=True)
s2=dt1.drop(s1.index)
print (s1.shape)
print  ( s2.shape)
s3=dt2.groupby('Label').apply(pd.DataFrame.sample, frac=0.5).reset_index(level='Label', drop=True)
s4=dt2.drop(s3.index)
print (s3.shape)
print  ( s4.shape)

(249603, 80)
(249607, 80)
(249605, 80)
(249606, 80)


In [5]:
s1.drop('Protocol',axis=1,inplace=True)
s1.drop('Dst Port',axis=1,inplace=True)
s2.drop('Protocol',axis=1,inplace=True)
s2.drop('Dst Port',axis=1,inplace=True)
s3.drop('Protocol',axis=1,inplace=True)
s3.drop('Dst Port',axis=1,inplace=True)
s4.drop('Protocol',axis=1,inplace=True)
s4.drop('Dst Port',axis=1,inplace=True)
print (s1.shape)
print  ( s2.shape)
print (s3.shape)
print  ( s4.shape)

(249603, 78)
(249607, 78)
(249605, 78)
(249606, 78)


In [7]:
s1.to_csv (r"C:\e\学习资料\02-03\data\data_process\split1.csv", header=True,index=0 )
s2.to_csv (r"C:\e\学习资料\02-03\data\data_process\split2.csv", header=True,index=0 )
s3.to_csv (r"C:\e\学习资料\02-03\data\data_process\split3.csv", header=True,index=0 )
s4.to_csv (r"C:\e\学习资料\02-03\data\data_process\split4.csv", header=True,index=0 )
print ('done')

done


In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.metrics import classification_report
from sklearn.svm import OneClassSVM
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
data1=pd.read_csv(r"C:\e\学习资料\02-03\data\data_process\split1.csv")
print (data1.shape )

(249603, 78)


In [3]:
labelt=data1.Label.copy()
print ( labelt.value_counts())
arrs=labelt.values
d1=np.array(arrs)
values = array(d1)
print(values)
# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
data3 = pd.DataFrame(integer_encoded) # header:原第一行的索引，index:原第一列的索引
#data3.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\ptrain1\ptrain2_sli2_labeln.csv",header=None,index=0)
# # binary encode
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)
data4 = pd.DataFrame(onehot_encoded) # header:原第一行的索引，index:原第一列的索引
#data4.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\ptrain1\tr1\t\f2_label.csv",header=None,index=0)

Benign                      47649
DoS attacks-Hulk            40417
DDOS attack-HOIC            30870
FTP-BruteForce              24170
SSH-Bruteforce              23448
DDoS attacks-LOIC-HTTP      21607
Infilteration               20242
Bot                         17887
DoS attacks-SlowHTTPTest    12240
DoS attacks-GoldenEye        8302
DoS attacks-Slowloris        2198
DDOS attack-LOIC-UDP          432
Brute Force -Web               90
Brute Force -XSS               38
SQL Injection                  13
Name: Label, dtype: int64
['Benign' 'Benign' 'Benign' ... 'SSH-Bruteforce' 'SSH-Bruteforce'
 'SSH-Bruteforce']
[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]


In [4]:
data4.to_csv(r"C:\e\学习资料\02-03\data\data_process\split1_label.csv",header=None,index=0)


In [5]:
dt2=pd.read_csv(r"C:\e\学习资料\02-03\data\data_process\split2.csv")

In [7]:
s1=dt2.groupby('Label').apply(pd.DataFrame.sample, frac=0.2).reset_index(level='Label', drop=True)
s2=dt2.drop ( s1.index )
print ( s1.shape )
print ( s2.shape )

(49921, 78)
(199686, 78)


In [8]:
s1.to_csv(r"C:\e\学习资料\02-03\data\data_process\split2_s1.csv", header=True,index=0 )
s2.to_csv(r"C:\e\学习资料\02-03\data\data_process\split2_s2.csv", header=True,index=0 )

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.metrics import classification_report
from sklearn.svm import OneClassSVM
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
X = pd.read_csv(r"C:\e\学习资料\02-03\data\data_process\split1_bert2.csv", header=None)
Y = pd.read_csv(r"C:\e\学习资料\02-03\data\data_process\split1_label.csv",header=None)
data1=pd.read_csv(r"C:\e\学习资料\02-03\data\data_process\split1.csv")
print ( data1.shape)
print  (X.shape)


(249603, 78)
(249603, 768)


In [2]:
print ( Y.shape)


(249603, 15)


In [3]:
labelt=data1.Label.copy()
print ( labelt.shape)

(249603,)


In [4]:
print ( labelt[0])

Benign


In [5]:
X = pd.concat ( [X,labelt],axis=1)
print ( X.shape)
print ( X.value_counts('Label'))

(249603, 769)
Label
Benign                      47649
DoS attacks-Hulk            40417
DDOS attack-HOIC            30870
FTP-BruteForce              24170
SSH-Bruteforce              23448
DDoS attacks-LOIC-HTTP      21607
Infilteration               20242
Bot                         17887
DoS attacks-SlowHTTPTest    12240
DoS attacks-GoldenEye        8302
DoS attacks-Slowloris        2198
DDOS attack-LOIC-UDP          432
Brute Force -Web               90
Brute Force -XSS               38
SQL Injection                  13
dtype: int64


In [5]:

ptx=X.drop (X[(X.Label=='SQL Injection')|(X.Label=='Brute Force -XSS')|(X.Label=='Brute Force -Web')|(X.Label=='DDOS attack-LOIC-UDP')|(X.Label=='DoS attacks-Slowloris' )].index)
#ptf2=ptf.drop (ptf[(ptf.Label=='SQL Injection')|(ptf.Label=='Brute Force -XSS')|(ptf.Label=='Brute Force -Web')|(ptf.Label=='DDOS attack-LOIC-UDP')|(ptf.Label=='DoS attacks-Slowloris' )].index)
print ( ptx.shape)
#print ( ptf2.shape )
print (ptx.value_counts('Label') )

(249603, 769)
(246832, 769)
Label
Benign                      47649
DoS attacks-Hulk            40417
DDOS attack-HOIC            30870
FTP-BruteForce              24170
SSH-Bruteforce              23448
DDoS attacks-LOIC-HTTP      21607
Infilteration               20242
Bot                         17887
DoS attacks-SlowHTTPTest    12240
DoS attacks-GoldenEye        8302
dtype: int64


In [7]:
#X = pd.concat ( [X,Y],axis=1)
print ( X.shape)
sp1=X.groupby('Label').apply(pd.DataFrame.sample, frac=0.6).reset_index(level='Label', drop=True)
sp2=X.drop ( sp1.index)
print ( sp1.shape)
print ( sp2.shape)

(249603, 784)
(149761, 784)
(99842, 784)


In [9]:
sp1_x = sp1.iloc[:,0:768]
print ( sp1_x.shape)
sp1_y = sp1.iloc[:,769:784]
print ( sp1_y.shape)

(149761, 768)
(149761, 15)


In [10]:
sp1_x.to_csv(r"C:\e\学习资料\02-03\data\data_process\sp1\d2\split1_s1.csv", header=None,index=0 )
sp1_y.to_csv(r"C:\e\学习资料\02-03\data\data_process\sp1\d2\split1_s1_y.csv", header=None,index=0 )

In [11]:
sp2_x = sp2.iloc[:,0:768]
print ( sp2_x.shape)
sp2_y = sp2.iloc[:,769:784]
print ( sp2_y.shape)

(99842, 768)
(99842, 15)


In [12]:
sp2_x.to_csv(r"C:\e\学习资料\02-03\data\data_process\sp1\d2\split1_s2.csv", header=None,index=0 )
sp2_y.to_csv(r"C:\e\学习资料\02-03\data\data_process\sp1\d2\split1_s2_y.csv", header=None,index=0 )

In [12]:
arrs=sp1_y.values
d1=np.array(arrs)
values = array(d1)
print(values)
# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
data3 = pd.DataFrame(integer_encoded) # header:原第一行的索引，index:原第一列的索引
#data3.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\ptrain1\ptrain2_sli2_labeln.csv",header=None,index=0)
# # binary encode
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)
data4 = pd.DataFrame(onehot_encoded) # header:原第一行的索引，index:原第一列的索引
data4.to_csv(r"C:\e\学习资料\02-03\data\data_process\sp1\d1\split1_s1_y.csv",header=None,index=0)

['Benign' 'Benign' 'Benign' ... 'SSH-Bruteforce' 'SSH-Bruteforce'
 'SSH-Bruteforce']
[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]


In [13]:
arrs=sp2_y.values
d1=np.array(arrs)
values = array(d1)
print(values)
# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
data3 = pd.DataFrame(integer_encoded) # header:原第一行的索引，index:原第一列的索引
#data3.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\ptrain1\ptrain2_sli2_labeln.csv",header=None,index=0)
# # binary encode
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)
data4 = pd.DataFrame(onehot_encoded) # header:原第一行的索引，index:原第一列的索引
data4.to_csv(r"C:\e\学习资料\02-03\data\data_process\sp1\d1\split1_s2_y.csv",header=None,index=0)

['Benign' 'Benign' 'Benign' ... 'SSH-Bruteforce' 'SSH-Bruteforce'
 'SSH-Bruteforce']
[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]


In [13]:
print (data1.shape)

(249603, 78)


In [22]:
d1=data1.groupby('Label').apply(pd.DataFrame.sample, frac=0.18).reset_index(level='Label', drop=True)
d2=data1.drop ( d1.index)
print (d1.shape )
print ( d2.shape)

(44930, 78)
(204673, 78)


In [23]:
d1.to_csv(r"C:\e\学习资料\02-03\data\data_process\sp1\d3\split1_d1.csv", header=True,index=0 )

In [24]:
d1=d2.groupby('Label').apply(pd.DataFrame.sample, frac=0.2).reset_index(level='Label', drop=True)
d2=d2.drop ( d1.index)
print (d1.shape )
print ( d2.shape)

(40934, 78)
(163739, 78)


In [25]:
d1.to_csv(r"C:\e\学习资料\02-03\data\data_process\sp1\d3\split1_d2.csv", header=True,index=0 )

In [26]:
d1=d2.groupby('Label').apply(pd.DataFrame.sample, frac=0.25).reset_index(level='Label', drop=True)
d2=d2.drop ( d1.index)
print (d1.shape )
print ( d2.shape)
d1.to_csv(r"C:\e\学习资料\02-03\data\data_process\sp1\d3\split1_d3.csv", header=True,index=0 )

(40936, 78)
(122803, 78)


In [27]:
d1=d2.groupby('Label').apply(pd.DataFrame.sample, frac=0.33).reset_index(level='Label', drop=True)
d2=d2.drop ( d1.index)
print (d1.shape )
print ( d2.shape)
d1.to_csv(r"C:\e\学习资料\02-03\data\data_process\sp1\d3\split1_d4.csv", header=True,index=0 )

(40525, 78)
(82278, 78)


In [28]:
d1=d2.groupby('Label').apply(pd.DataFrame.sample, frac=0.5).reset_index(level='Label', drop=True)
d2=d2.drop ( d1.index)
print (d1.shape )
print ( d2.shape)
d1.to_csv(r"C:\e\学习资料\02-03\data\data_process\sp1\d3\split1_d5.csv", header=True,index=0 )
d2.to_csv(r"C:\e\学习资料\02-03\data\data_process\sp1\d3\split1_d6.csv", header=True,index=0 )

(41138, 78)
(41140, 78)
