In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.metrics import classification_report
from sklearn.svm import OneClassSVM
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
df=pd.read_csv(r"C:\e\学习资料\02-03\ptrain1.csv")
df.drop_duplicates( keep=False)
print ( df.shape)
print ( df.shape)

C:\d\anaconda\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning: Columns (0,1,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


(1222654, 80)
(1222654, 80)


In [2]:
df.drop_duplicates( keep=False,inplace=True)

In [8]:
df.drop('Protocol',axis=1,inplace=True)
df.drop('Dst Port',axis=1,inplace=True)
print ( df.shape)

(1174778, 78)


In [9]:
print ( df.shape )

for index in df.columns:
    df[index]=df[index].fillna(0)
    df[index]=df[index].replace(np.Infinity,1)

#X.drop ( columus=[77],axis=1,inplace=True)
#X.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\pva1\pva_1.csv", header=None,index=0)
print (df.shape)

df1=df.drop (df[(df.Label=='Benign')].index)
df2 = df.drop ( df1.index)

(1174778, 78)
(1174778, 78)


In [10]:
print ( df2.shape)

(900405, 78)


In [11]:
df2.value_counts('Label')

Label
Benign    900405
dtype: int64

In [12]:
benign1=df2.groupby('Label').apply(pd.DataFrame.sample, frac=0.2).reset_index(level='Label', drop=True)
benign2= df2.drop ( benign1.index)
print ( benign1.value_counts('Label'))
print ( benign2.value_counts('Label'))

Label
Benign    180081
dtype: int64
Label
Benign    720324
dtype: int64


In [13]:
benign1.to_csv (r"C:\e\学习资料\02-03\data\data_process\benign\benign1.csv", header=True,index=0 )
benign2.to_csv (r"C:\e\学习资料\02-03\data\data_process\benign\benign2.csv", header=True,index=0 )

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.metrics import classification_report
from sklearn.svm import OneClassSVM
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

dataset = pd.read_csv(r"C:\e\学习资料\02-03\data\data_process\3\split3new_s3.csv")
benign = pd.read_csv(r"C:\e\学习资料\02-03\data\data_process\benign\benign3.csv")
print (dataset.value_counts('Label'))
print ( dataset.shape )
print ( benign.shape )

Label
DoS attacks-Hulk            40187
DDOS attack-HOIC            30828
DDoS attacks-LOIC-HTTP      21607
SSH-Bruteforce              20159
Infilteration               18109
Bot                         17868
FTP-BruteForce              14112
DoS attacks-GoldenEye        8302
DoS attacks-SlowHTTPTest     6731
dtype: int64
(177903, 78)
(183683, 78)


In [2]:
merge = dataset.append (benign)
print ( merge.shape )

(361586, 78)


In [3]:
print ( merge.value_counts('Label'))

Label
Benign                      183683
DoS attacks-Hulk             40187
DDOS attack-HOIC             30828
DDoS attacks-LOIC-HTTP       21607
SSH-Bruteforce               20159
Infilteration                18109
Bot                          17868
FTP-BruteForce               14112
DoS attacks-GoldenEye         8302
DoS attacks-SlowHTTPTest      6731
dtype: int64


In [8]:
labelt=merge.Label.copy()
print ( labelt.value_counts())
arrs=labelt.values
d1=np.array(arrs)
values = array(d1)
print(values)
# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
data3 = pd.DataFrame(integer_encoded) # header:原第一行的索引，index:原第一列的索引
#data3.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\ptrain1\ptrain2_sli2_labeln.csv",header=None,index=0)
# # binary encode
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)
data4 = pd.DataFrame(onehot_encoded) # header:原第一行的索引，index:原第一列的索引
data4.to_csv(r"C:\e\学习资料\02-03\data\data_process\3\split3news3_benign.csv",header=None,index=0)

Benign                      183683
DoS attacks-Hulk             40187
DDOS attack-HOIC             30828
DDoS attacks-LOIC-HTTP       21607
SSH-Bruteforce               20159
Infilteration                18109
Bot                          17868
FTP-BruteForce               14112
DoS attacks-GoldenEye         8302
DoS attacks-SlowHTTPTest      6731
Name: Label, dtype: int64
['Bot' 'Bot' 'Bot' ... 'Benign' 'Benign' 'Benign']
[[0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]


In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.metrics import classification_report
from sklearn.svm import OneClassSVM
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
df=pd.read_csv(r"C:\e\学习资料\02-03\data\data_process\benign\benign2.csv")
#df.drop_duplicates( keep=False)
print ( df.shape )
df.value_counts('Label')

(720324, 78)


Label
Benign    720324
dtype: int64

In [3]:
benign1=df.groupby('Label').apply(pd.DataFrame.sample, frac=0.25).reset_index(level='Label', drop=True)
benign2= df.drop ( benign1.index)
print ( benign1.value_counts('Label'))
print ( benign2.value_counts('Label'))

Label
Benign    180081
dtype: int64
Label
Benign    540243
dtype: int64


In [5]:
benign3=benign2.groupby('Label').apply(pd.DataFrame.sample, frac=0.34).reset_index(level='Label', drop=True)
benign4= benign2.drop ( benign3.index)
print ( benign3.value_counts('Label'))
print ( benign4.value_counts('Label'))

Label
Benign    183683
dtype: int64
Label
Benign    356560
dtype: int64


In [6]:
print ( benign1.shape )
print ( benign3.shape )

(180081, 78)
(183683, 78)


In [7]:
benign1.to_csv (r"C:\e\学习资料\02-03\data\data_process\benign\benign2.csv", header=True,index=0 )
benign3.to_csv (r"C:\e\学习资料\02-03\data\data_process\benign\benign3.csv", header=True,index=0 )

In [8]:
print ( benign4.shape )
benign4.to_csv (r"C:\e\学习资料\02-03\data\data_process\benign\benign4.csv", header=True,index=0 )

(356560, 78)


In [8]:
labelt=merge.groupby('Label').apply(pd.DataFrame.sample, frac=0.04).reset_index(level='Label', drop=True)
lt1=labelt.Label.copy()
print ( lt1.shape )
print ( lt1.value_counts())

(14461,)
Benign                      7347
DoS attacks-Hulk            1607
DDOS attack-HOIC            1233
DDoS attacks-LOIC-HTTP       864
SSH-Bruteforce               806
Infilteration                724
Bot                          715
FTP-BruteForce               564
DoS attacks-GoldenEye        332
DoS attacks-SlowHTTPTest     269
Name: Label, dtype: int64


In [9]:
lt1.to_csv(r"C:\e\学习资料\02-03\data\data_process\3\sample.csv",header=True,index=0)

In [10]:
lt2 = pd.read_csv(r"C:\e\学习资料\02-03\data\data_process\3\sample.csv")
print ( lt2.shape )
print ( lt2.value_counts())

(14461, 1)
Label                   
Benign                      7347
DoS attacks-Hulk            1607
DDOS attack-HOIC            1233
DDoS attacks-LOIC-HTTP       864
SSH-Bruteforce               806
Infilteration                724
Bot                          715
FTP-BruteForce               564
DoS attacks-GoldenEye        332
DoS attacks-SlowHTTPTest     269
dtype: int64


In [12]:
arrs=lt1.values
d1=np.array(arrs)
values = array(d1)
print(values)
# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
data3 = pd.DataFrame(integer_encoded) # header:原第一行的索引，index:原第一列的索引
#data3.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\ptrain1\ptrain2_sli2_labeln.csv",header=None,index=0)
# # binary encode
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)
data4 = pd.DataFrame(onehot_encoded) # header:原第一行的索引，index:原第一列的索引
data4.to_csv(r"C:\e\学习资料\02-03\data\data_process\3\sample2.csv",header=None,index=0)

['Benign' 'Benign' 'Benign' ... 'SSH-Bruteforce' 'SSH-Bruteforce'
 'SSH-Bruteforce']
[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]
