In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.metrics import classification_report
from sklearn.svm import OneClassSVM
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
df=pd.read_csv(r"C:\e\学习资料\02-03\ptrain1.csv")
df.drop_duplicates( keep=False)
print ( df.shape)
print ( df.shape)

C:\d\anaconda\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning: Columns (0,1,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


(1222654, 80)
(1222654, 80)


In [2]:
df.drop_duplicates( keep=False,inplace=True)

In [3]:
print ( df.shape)

(1174778, 80)


In [4]:
df.drop('Protocol',axis=1,inplace=True)
df.drop('Dst Port',axis=1,inplace=True)
df.drop('Timestamp',axis=1,inplace=True)

In [5]:
print ( df.shape)

(1174778, 77)


In [6]:
df.value_counts('Label')

Label
Benign                      900405
DDOS attack-HOIC            100090
DoS attacks-Hulk             66484
Bot                          41887
Infilteration                24996
SSH-Bruteforce               20085
FTP-BruteForce                8483
DoS attacks-GoldenEye         6099
DoS attacks-SlowHTTPTest      4311
DoS attacks-Slowloris         1547
DDOS attack-LOIC-UDP           254
Brute Force -Web                90
Brute Force -XSS                34
SQL Injection                   13
dtype: int64

In [7]:
print ( df.shape )

for index in df.columns:
    df[index]=df[index].fillna(0)
    df[index]=df[index].replace(np.Infinity,1)

#X.drop ( columus=[77],axis=1,inplace=True)
#X.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\pva1\pva_1.csv", header=None,index=0)
print (df.shape)

(1174778, 77)
(1174778, 77)


In [16]:
pt1=df.groupby('Label').apply(pd.DataFrame.sample, frac=0.5).reset_index(level='Label', drop=True)
ptf=df.drop(pt1.index)
pt1.value_counts("Label")
print ( pt1.shape)
print ( ptf.shape)

(587390, 77)
(587388, 77)


In [17]:
pt2=pt1.drop (pt1[(pt1.Label=='SQL Injection')|(pt1.Label=='Brute Force -XSS')|(pt1.Label=='Brute Force -Web')|(pt1.Label=='DDOS attack-LOIC-UDP')|(pt1.Label=='DoS attacks-Slowloris' )].index)
ptf2=ptf.drop (ptf[(ptf.Label=='SQL Injection')|(ptf.Label=='Brute Force -XSS')|(ptf.Label=='Brute Force -Web')|(ptf.Label=='DDOS attack-LOIC-UDP')|(ptf.Label=='DoS attacks-Slowloris' )].index)
print ( pt2.shape)
print ( ptf2.shape )
#df = df.drop(df[(df.ts_code >= "500000") & (df.ts_code < "600000")].index)

(586421, 77)
(586419, 77)


In [18]:
pt2.value_counts("Label")

Label
Benign                      450202
DDOS attack-HOIC             50045
DoS attacks-Hulk             33242
Bot                          20944
Infilteration                12498
SSH-Bruteforce               10042
FTP-BruteForce                4242
DoS attacks-GoldenEye         3050
DoS attacks-SlowHTTPTest      2156
dtype: int64

In [19]:
t1=pt2.groupby('Label').apply(pd.DataFrame.sample, frac=0.5).reset_index(level='Label', drop=True)
f1=ptf2.groupby('Label').apply(pd.DataFrame.sample, frac=0.5).reset_index(level='Label', drop=True)
t2=pt2.drop(t1.index)
print ( t1.shape )
print ( t2.shape )
print ( f1.shape )

(293210, 77)
(293211, 77)
(293210, 77)


In [20]:
t2.value_counts("Label")

Label
Benign                      225101
DDOS attack-HOIC             25023
DoS attacks-Hulk             16621
Bot                          10472
Infilteration                 6249
SSH-Bruteforce                5021
FTP-BruteForce                2121
DoS attacks-GoldenEye         1525
DoS attacks-SlowHTTPTest      1078
dtype: int64

In [16]:
t1.to_csv (r"E:\学习心得\data\cic-ids2018\02-03\ptrain1\tr1\sptrain1_1.csv", header=None,index=0 )
t2.to_csv (r"E:\学习心得\data\cic-ids2018\02-03\ptrain1\tr1\sptrain1_t1.csv", header=None,index=0 )

print ( "!")

!


In [25]:
t1_1=t1.groupby('Label').apply(pd.DataFrame.sample, frac=0.15).reset_index(level='Label', drop=True)
t2_1=t2.groupby('Label').apply(pd.DataFrame.sample, frac=0.15).reset_index(level='Label', drop=True)
f1_1=f1.groupby('Label').apply(pd.DataFrame.sample, frac=0.15).reset_index(level='Label', drop=True)
f1_11=f1_1.groupby('Label').apply(pd.DataFrame.sample, frac=0.5).reset_index(level='Label', drop=True)
f1_12=f1_1.drop(f1_11.index)
print ( t1_1.shape )
print ( t2_1.shape )
print ( f1_11.shape)
print ( f1_12.shape)

(43981, 77)
(43981, 77)
(21988, 77)
(21993, 77)


In [19]:
t1_1.value_counts('Label')

Label
Benign                      67530
DDOS attack-HOIC             7507
DoS attacks-Hulk             4986
Bot                          3142
Infilteration                1875
SSH-Bruteforce               1506
FTP-BruteForce                636
DoS attacks-GoldenEye         458
DoS attacks-SlowHTTPTest      323
dtype: int64

In [20]:
t2_1.value_counts('Label')

Label
Benign                      67530
DDOS attack-HOIC             7507
DoS attacks-Hulk             4986
Bot                          3142
Infilteration                1875
SSH-Bruteforce               1506
FTP-BruteForce                636
DoS attacks-GoldenEye         458
DoS attacks-SlowHTTPTest      323
dtype: int64

In [21]:
t1_1.to_csv (r"E:\学习心得\data\cic-ids2018\02-03\ptrain1\tr1\sptrain1_t1_1.csv", header=None,index=0 )
t2_1.to_csv (r"E:\学习心得\data\cic-ids2018\02-03\ptrain1\tr1\sptrain1_t2-1.csv", header=None,index=0 )
print ( "!")

!


In [3]:
t1_2=t1_1.groupby('Label').apply(pd.DataFrame.sample, frac=0.5).reset_index(level='Label', drop=True)
t2_2=t2_1.groupby('Label').apply(pd.DataFrame.sample, frac=0.5).reset_index(level='Label', drop=True)
print ( t1_2.shape )
print ( t2_2.shape )
t1_2.value_counts('Label')
t2_2.value_counts('Label')

NameError: name 't1_1' is not defined

In [23]:
t2_2.value_counts('Label')


Label
Benign                      33765
DDOS attack-HOIC             3754
DoS attacks-Hulk             2493
Bot                          1571
Infilteration                 938
SSH-Bruteforce                753
FTP-BruteForce                318
DoS attacks-GoldenEye         229
DoS attacks-SlowHTTPTest      162
dtype: int64

In [26]:
print ( t1_1.shape )
print ( t2_1.shape )
print ( f1_11.shape)
print ( f1_12.shape)
t1_1.to_csv (r"E:\学习心得\data\cic-ids2018\02-03\ptrain1\tr1\t\sptrain1_t1.csv", header=None,index=0 )
t2_1.to_csv (r"E:\学习心得\data\cic-ids2018\02-03\ptrain1\tr1\t\sptrain1_t2.csv", header=None,index=0 )
f1_11.to_csv (r"E:\学习心得\data\cic-ids2018\02-03\ptrain1\tr1\t\sptrain1_f1.csv", header=None,index=0 )
f1_12.to_csv (r"E:\学习心得\data\cic-ids2018\02-03\ptrain1\tr1\t\sptrain1_f2.csv", header=None,index=0 )

print ( "!")

(43981, 77)
(43981, 77)
(21988, 77)
(21993, 77)
!


In [3]:
import pandas as pd
bt1=pd.read_csv(r"E:\学习心得\data\cic-ids2018\02-03\ptrain1\tr1\sptrain1_1_bert.csv")
bt2=pd.read_csv(r"E:\学习心得\data\cic-ids2018\02-03\ptrain1\tr1\sptrain1_1_bert.csv")
print ( bt1.shape )


(43982, 768)


In [4]:
print ( bt2.shape )

(43982, 768)


In [27]:
labelt=t1_1.Label.copy()
print ( labelt.value_counts())
arrs=labelt.values
d1=np.array(arrs)
values = array(d1)
print(values)
# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
data3 = pd.DataFrame(integer_encoded) # header:原第一行的索引，index:原第一列的索引
#data3.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\ptrain1\ptrain2_sli2_labeln.csv",header=None,index=0)
# # binary encode
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)
data4 = pd.DataFrame(onehot_encoded) # header:原第一行的索引，index:原第一列的索引
data4.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\ptrain1\tr1\t\t1_label.csv",header=None,index=0)

Benign                      33765
DDOS attack-HOIC             3753
DoS attacks-Hulk             2493
Bot                          1571
Infilteration                 937
SSH-Bruteforce                753
FTP-BruteForce                318
DoS attacks-GoldenEye         229
DoS attacks-SlowHTTPTest      162
Name: Label, dtype: int64
['Benign' 'Benign' 'Benign' ... 'SSH-Bruteforce' 'SSH-Bruteforce'
 'SSH-Bruteforce']
[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]


In [28]:
labelt=t2_1.Label.copy()
print ( labelt.value_counts())
arrs=labelt.values
d1=np.array(arrs)
values = array(d1)
print(values)
# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
data3 = pd.DataFrame(integer_encoded) # header:原第一行的索引，index:原第一列的索引
#data3.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\ptrain1\ptrain2_sli2_labeln.csv",header=None,index=0)
# # binary encode
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)
data4 = pd.DataFrame(onehot_encoded) # header:原第一行的索引，index:原第一列的索引
data4.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\ptrain1\tr1\t\t2_label.csv",header=None,index=0)

Benign                      33765
DDOS attack-HOIC             3753
DoS attacks-Hulk             2493
Bot                          1571
Infilteration                 937
SSH-Bruteforce                753
FTP-BruteForce                318
DoS attacks-GoldenEye         229
DoS attacks-SlowHTTPTest      162
Name: Label, dtype: int64
['Benign' 'Benign' 'Benign' ... 'SSH-Bruteforce' 'SSH-Bruteforce'
 'SSH-Bruteforce']
[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]


In [29]:
labelt=f1_11.Label.copy()
print ( labelt.value_counts())
arrs=labelt.values
d1=np.array(arrs)
values = array(d1)
print(values)
# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
data3 = pd.DataFrame(integer_encoded) # header:原第一行的索引，index:原第一列的索引
#data3.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\ptrain1\ptrain2_sli2_labeln.csv",header=None,index=0)
# # binary encode
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)
data4 = pd.DataFrame(onehot_encoded) # header:原第一行的索引，index:原第一列的索引
data4.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\ptrain1\tr1\t\f1_label.csv",header=None,index=0)

Benign                      16882
DDOS attack-HOIC             1876
DoS attacks-Hulk             1246
Bot                           786
Infilteration                 468
SSH-Bruteforce                376
FTP-BruteForce                159
DoS attacks-GoldenEye         114
DoS attacks-SlowHTTPTest       81
Name: Label, dtype: int64
['Benign' 'Benign' 'Benign' ... 'SSH-Bruteforce' 'SSH-Bruteforce'
 'SSH-Bruteforce']
[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]


In [30]:
labelt=f1_12.Label.copy()
print ( labelt.value_counts())
arrs=labelt.values
d1=np.array(arrs)
values = array(d1)
print(values)
# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
data3 = pd.DataFrame(integer_encoded) # header:原第一行的索引，index:原第一列的索引
#data3.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\ptrain1\ptrain2_sli2_labeln.csv",header=None,index=0)
# # binary encode
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)
data4 = pd.DataFrame(onehot_encoded) # header:原第一行的索引，index:原第一列的索引
data4.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\ptrain1\tr1\t\f2_label.csv",header=None,index=0)

Benign                      16883
DDOS attack-HOIC             1877
DoS attacks-Hulk             1247
Bot                           785
Infilteration                 469
SSH-Bruteforce                377
FTP-BruteForce                159
DoS attacks-GoldenEye         115
DoS attacks-SlowHTTPTest       81
Name: Label, dtype: int64
['Benign' 'Benign' 'Benign' ... 'SSH-Bruteforce' 'SSH-Bruteforce'
 'SSH-Bruteforce']
[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]


In [2]:
t1_2.to_csv (r"E:\学习心得\data\cic-ids2018\02-03\ptrain1\tr1\sptrain1_t1_1.csv", header=None,index=0 )
t2_2.to_csv (r"E:\学习心得\data\cic-ids2018\02-03\ptrain1\tr1\sptrain1_t2-1.csv", header=None,index=0 )
print ( "!")

NameError: name 't1_2' is not defined

In [1]:
t1_2.value_counts('Label')

NameError: name 't1_2' is not defined

In [5]:
import pandas as pd
import numpy as np
from tensorflow.keras import Model
import tensorflow as tf
np.random.seed(1337)  # for reproducibility
from keras.preprocessing import sequence
from keras.utils.np_utils import to_categorical
from sklearn.metrics import (precision_score, recall_score,
                             f1_score, accuracy_score,mean_squared_error,mean_absolute_error)
from sklearn import metrics
from sklearn.preprocessing import Normalizer

X = pd.read_csv(r"E:\学习心得\data\cic-ids2018\02-03\ptrain1\tr1\sptrain1_t1_1.csv", header=None)
#Y = pd.read_csv(r"E:\学习心得\data\cic-ids2018\02-03\ptrain1\tr1\t1_2_label.csv", header=None)

T = pd.read_csv(r"E:\学习心得\data\cic-ids2018\02-03\ptrain1\tr1\sptrain1_t2-1.csv", header=None)
#C = pd.read_csv(r"E:\学习心得\data\cic-ids2018\02-03\ptrain1\tr1\t2_2_label.csv", header=None)

In [8]:
print (X.isnull().any())

0     False
1     False
2     False
3     False
4     False
      ...  
72    False
73    False
74    False
75    False
76    False
Length: 77, dtype: bool


In [8]:
df1=df.drop (df[(df.Label=='SQL Injection')|(df.Label=='Brute Force -XSS')|(df.Label=='Brute Force -Web')|(df.Label=='DDOS attack-LOIC-UDP')|(df.Label=='DoS attacks-Slowloris' )].index)
df2=df.drop (df1.index)
print ( df1.shape)
print ( df2.shape )

(1172840, 77)
(1938, 77)


In [9]:
df1.value_counts('Label')

Label
Benign                      900405
DDOS attack-HOIC            100090
DoS attacks-Hulk             66484
Bot                          41887
Infilteration                24996
SSH-Bruteforce               20085
FTP-BruteForce                8483
DoS attacks-GoldenEye         6099
DoS attacks-SlowHTTPTest      4311
dtype: int64

In [10]:
df2.value_counts('Label')

Label
DoS attacks-Slowloris    1547
DDOS attack-LOIC-UDP      254
Brute Force -Web           90
Brute Force -XSS           34
SQL Injection              13
dtype: int64

In [11]:
df1_1=df1.drop (df1[(df1.Label=='Benign')].index)
df1_2=df1.drop (df1_1.index)
print ( df1_1.shape)
print ( df1_2.shape )

(272435, 77)
(900405, 77)


In [13]:
df1_1.value_counts('Label')
#df1_2.value_counts('Label')

Label
DDOS attack-HOIC            100090
DoS attacks-Hulk             66484
Bot                          41887
Infilteration                24996
SSH-Bruteforce               20085
FTP-BruteForce                8483
DoS attacks-GoldenEye         6099
DoS attacks-SlowHTTPTest      4311
dtype: int64

In [14]:
df1_2_1 = df1_2.groupby('Label').apply(pd.DataFrame.sample, frac=0.18).reset_index(level='Label', drop=True)
df1_2_1.value_counts('Label')

Label
Benign    162073
dtype: int64

In [17]:
pn1 = pd.concat ( [df1_1,df1_2_1],axis=0)
print ( pn1.shape)


(434508, 77)


In [18]:
pn1.value_counts('Label')

Label
Benign                      162073
DDOS attack-HOIC            100090
DoS attacks-Hulk             66484
Bot                          41887
Infilteration                24996
SSH-Bruteforce               20085
FTP-BruteForce                8483
DoS attacks-GoldenEye         6099
DoS attacks-SlowHTTPTest      4311
dtype: int64

In [19]:
pn1.to_csv(r"C:\e\学习资料\02-03\ptrain_1\ptr1.csv",header=True,index=0)

In [20]:
df2.value_counts('Label')

Label
DoS attacks-Slowloris    1547
DDOS attack-LOIC-UDP      254
Brute Force -Web           90
Brute Force -XSS           34
SQL Injection              13
dtype: int64

In [21]:
df2.to_csv(r"C:\e\学习资料\02-03\ptrain_1\ptrf.csv",header=True,index=0)

In [22]:
pn1_t = pn1.groupby('Label').apply(pd.DataFrame.sample, frac=0.1).reset_index(level='Label', drop=True)

In [23]:
pn1_t.value_counts('Label')

Label
Benign                      16207
DDOS attack-HOIC            10009
DoS attacks-Hulk             6648
Bot                          4189
Infilteration                2500
SSH-Bruteforce               2008
FTP-BruteForce                848
DoS attacks-GoldenEye         610
DoS attacks-SlowHTTPTest      431
dtype: int64

In [24]:
pn1_t2=pn1.drop ( pn1_t.index)
pn1_t2.value_counts('Label')

Label
Benign                      145866
DDOS attack-HOIC             90081
DoS attacks-Hulk             59836
Bot                          37698
Infilteration                22496
SSH-Bruteforce               18077
FTP-BruteForce                7635
DoS attacks-GoldenEye         5489
DoS attacks-SlowHTTPTest      3880
dtype: int64

In [25]:
pn1_t2.to_csv(r"C:\e\学习资料\02-03\ptrain_1\ptr_2.csv",header=True,index=0)
pn1_t.to_csv(r"C:\e\学习资料\02-03\ptrain_1\ptr_1.csv",header=True,index=0)


In [30]:
print ( pn1_t2.shape)

(391058, 77)


In [29]:
arrs=pn1_t.Label.copy()
d1=np.array(arrs)
values = array(d1)
print(values)
# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
data3 = pd.DataFrame(integer_encoded) # header:原第一行的索引，index:原第一列的索引
#data3.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\ptrain1\ptrain2_sli2_labeln.csv",header=None,index=0)
# # binary encode
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)
data4 = pd.DataFrame(onehot_encoded) # header:原第一行的索引，index:原第一列的索引
data4.to_csv(r"C:\e\学习资料\02-03\ptrain_1\ptr_1_by.csv",header=None,index=0)

['Benign' 'Benign' 'Benign' ... 'SSH-Bruteforce' 'SSH-Bruteforce'
 'SSH-Bruteforce']
[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]


In [31]:
pn1_t21 = pn1_t2.groupby('Label').apply(pd.DataFrame.sample, frac=0.33).reset_index(level='Label', drop=True)
pn1_t22 = pn1.drop (pn1_t21.index)
print ( pn1_t21.shape)
print ( pn1_t22.shape)

(129049, 77)
(305459, 77)


In [32]:
pn1_t21.to_csv(r"C:\e\学习资料\02-03\ptrain_1\ptr_21.csv",header=True,index=0)
pn1_t22.to_csv(r"C:\e\学习资料\02-03\ptrain_1\ptr_22.csv",header=True,index=0)

In [33]:
arrs=pn1_t21.Label.copy()
d1=np.array(arrs)
values = array(d1)
print(values)
# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
data3 = pd.DataFrame(integer_encoded) # header:原第一行的索引，index:原第一列的索引
#data3.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\ptrain1\ptrain2_sli2_labeln.csv",header=None,index=0)
# # binary encode
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)
data4 = pd.DataFrame(onehot_encoded) # header:原第一行的索引，index:原第一列的索引
data4.to_csv(r"C:\e\学习资料\02-03\ptrain_1\ptr_21_by.csv",header=None,index=0)

['Benign' 'Benign' 'Benign' ... 'SSH-Bruteforce' 'SSH-Bruteforce'
 'SSH-Bruteforce']
[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]
