In [36]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.metrics import classification_report
from sklearn.svm import OneClassSVM

d1=pd.read_csv(r"C:\e\学习资料\02-03\data\Friday-02-03-2018_TrafficForML_CICFlowMeter.csv")
d1.columns
print ( d1.value_counts('Label'))

Label
Benign    762384
Bot       286191
dtype: int64


In [37]:
dt1=d1.groupby('Label').apply(pd.DataFrame.sample, frac=0.5).reset_index(level='Label', drop=True)
#pt2=pt1.drop (pt1[(pt1.Label=='SQL Injection')|(pt1.Label=='Brute Force -XSS')|(pt1.Label=='Brute Force -Web')|(pt1.Label=='DDOS attack-LOIC-UDP')|(pt1.Label=='DoS attacks-Slowloris' )].index)
#ptf2=ptf.drop (ptf[(ptf.Label=='SQL Injection')|(ptf.Label=='Brute Force -XSS')|(ptf.Label=='Brute Force -Web')|(ptf.Label=='DDOS attack-LOIC-UDP')|(ptf.Label=='DoS attacks-Slowloris' )].index)
d1_s=d1.drop (d1[(d1.Label=='Benign')].index)
print (d1_s.value_counts('Label'))
print ( dt1.value_counts('Label'))

Label
Bot    286191
dtype: int64
Label
Benign    381192
Bot       143096
dtype: int64


In [38]:
d2=pd.read_csv(r"C:\e\学习资料\02-03\data\Friday-16-02-2018_TrafficForML_CICFlowMeter.csv")
d2.columns
print ( d2.value_counts('Label'))

Label
DoS attacks-Hulk            461912
Benign                      446772
DoS attacks-SlowHTTPTest    139890
Label                            1
dtype: int64


In [39]:
d2=d2.drop (d2[(d2.Label=='Label')].index)
print ( d2.value_counts('Label'))

Label
DoS attacks-Hulk            461912
Benign                      446772
DoS attacks-SlowHTTPTest    139890
dtype: int64


In [40]:
d2_s=d2.drop (d2[(d2.Label=='Benign')].index)
print ( d2_s.value_counts('Label'))

Label
DoS attacks-Hulk            461912
DoS attacks-SlowHTTPTest    139890
dtype: int64


In [41]:
dt2_s=d2_s.groupby('Label').apply(pd.DataFrame.sample, frac=0.7).reset_index(level='Label', drop=True)
print ( dt2_s.value_counts('Label'))

Label
DoS attacks-Hulk            323338
DoS attacks-SlowHTTPTest     97923
dtype: int64


In [42]:
dt1=dt1.append(dt2_s)
print (dt1.value_counts('Label'))

Label
Benign                      381192
DoS attacks-Hulk            323338
Bot                         143096
DoS attacks-SlowHTTPTest     97923
dtype: int64


In [43]:
d2=pd.read_csv(r"C:\e\学习资料\02-03\data\Friday-23-02-2018_TrafficForML_CICFlowMeter.csv")
d2.columns
print ( d2.value_counts('Label'))

Label
Benign              1048009
Brute Force -Web        362
Brute Force -XSS        151
SQL Injection            53
dtype: int64


In [44]:
d3_s=d2.drop (d2[(d2.Label=='Benign')].index)
print ( d3_s.value_counts('Label'))

Label
Brute Force -Web    362
Brute Force -XSS    151
SQL Injection        53
dtype: int64


In [45]:
d4=pd.read_csv(r"C:\e\学习资料\02-03\data\Thuesday-20-02-2018_TrafficForML_CICFlowMeter.csv")
d4.columns
print ( d4.value_counts('Label'))

Label
Benign                    7372557
DDoS attacks-LOIC-HTTP     576191
dtype: int64


In [14]:
d4t=d4.groupby('Label').apply(pd.DataFrame.sample, frac=0.3).reset_index(level='Label', drop=True)

In [46]:
print ( d4t.value_counts('Label'))

Label
Benign                    2211767
DDoS attacks-LOIC-HTTP     172857
dtype: int64


In [48]:
d4t_s=d4t.drop ( d4t[(d4t.Label=='Benign')].index)

In [49]:
print ( d4t_s.value_counts('Label'))

Label
DDoS attacks-LOIC-HTTP    172857
dtype: int64


In [50]:
dt1=dt1.append(d4t_s)
print (dt1.value_counts('Label'))

Label
Benign                      381192
DoS attacks-Hulk            323338
DDoS attacks-LOIC-HTTP      172857
Bot                         143096
DoS attacks-SlowHTTPTest     97923
dtype: int64


In [51]:
dt1_1=dt1.groupby('Label').apply(pd.DataFrame.sample, frac=0.5).reset_index(level='Label', drop=True)
print (dt1_1.value_counts('Label'))

Label
Benign                      190596
DoS attacks-Hulk            161669
DDoS attacks-LOIC-HTTP       86428
Bot                          71548
DoS attacks-SlowHTTPTest     48962
dtype: int64


In [52]:
d5=pd.read_csv(r"C:\e\学习资料\02-03\data\Thursday-01-03-2018_TrafficForML_CICFlowMeter.csv")
d5.columns
print ( d5.value_counts('Label'))

Label
Benign           238037
Infilteration     93063
Label                25
dtype: int64


In [53]:
d5=d5.drop (d5[(d5.Label=='Benign')|(d5.Label=='Label')].index)
dt5=d5.groupby('Label').apply(pd.DataFrame.sample, frac=0.5).reset_index(level='Label', drop=True)
dt1_1=dt1_1.append ( dt5)
print (dt1_1.value_counts('Label'))

Label
Benign                      190596
DoS attacks-Hulk            161669
DDoS attacks-LOIC-HTTP       86428
Bot                          71548
DoS attacks-SlowHTTPTest     48962
Infilteration                46532
dtype: int64


In [54]:
d6=pd.read_csv(r"C:\e\学习资料\02-03\data\Thursday-15-02-2018_TrafficForML_CICFlowMeter.csv")
print ( d6.value_counts('Label'))

Label
Benign                   996077
DoS attacks-GoldenEye     41508
DoS attacks-Slowloris     10990
dtype: int64


In [55]:
d6=d6.drop (d6[(d6.Label=='Benign')].index)
dt6=d6.groupby('Label').apply(pd.DataFrame.sample, frac=0.8).reset_index(level='Label', drop=True)
dt1_1=dt1_1.append ( dt6)
print (dt1_1.value_counts('Label'))

Label
Benign                      190596
DoS attacks-Hulk            161669
DDoS attacks-LOIC-HTTP       86428
Bot                          71548
DoS attacks-SlowHTTPTest     48962
Infilteration                46532
DoS attacks-GoldenEye        33206
DoS attacks-Slowloris         8792
dtype: int64


In [56]:
d7=pd.read_csv(r"C:\e\学习资料\02-03\data\Thursday-22-02-2018_TrafficForML_CICFlowMeter.csv")
print ( d7.value_counts('Label'))

Label
Benign              1048213
Brute Force -Web        249
Brute Force -XSS         79
SQL Injection            34
dtype: int64


In [29]:
dt7=d7.drop (d7[(d7.Label=='Benign')].index)
d3_s=d3_s.append (dt7)
print ( d3_s.value_counts('Label'))

Label
Brute Force -Web    611
Brute Force -XSS    230
SQL Injection        87
dtype: int64


In [57]:
d8=pd.read_csv(r"C:\e\学习资料\02-03\data\Wednesday-14-02-2018_TrafficForML_CICFlowMeter.csv")
print ( d8.value_counts('Label'))

Label
Benign            667626
FTP-BruteForce    193360
SSH-Bruteforce    187589
dtype: int64


In [58]:
d8=d8.drop (d8[(d8.Label=='Benign')].index)
dt8=d8.groupby('Label').apply(pd.DataFrame.sample, frac=0.5).reset_index(level='Label', drop=True)
dt1_1=dt1_1.append ( dt8)
print (dt1_1.value_counts('Label'))

Label
Benign                      190596
DoS attacks-Hulk            161669
FTP-BruteForce               96680
SSH-Bruteforce               93794
DDoS attacks-LOIC-HTTP       86428
Bot                          71548
DoS attacks-SlowHTTPTest     48962
Infilteration                46532
DoS attacks-GoldenEye        33206
DoS attacks-Slowloris         8792
dtype: int64


In [32]:
d9=pd.read_csv(r"C:\e\学习资料\02-03\data\Wednesday-21-02-2018_TrafficForML_CICFlowMeter.csv")
print ( d9.value_counts('Label'))

Label
DDOS attack-HOIC        686012
Benign                  360833
DDOS attack-LOIC-UDP      1730
dtype: int64


In [59]:
d91=d9.drop (d9[(d9.Label=='Benign')|(d9.Label=='DDOS attack-HOIC')].index)
d92=d9.drop (d9[(d9.Label=='Benign')|(d9.Label=='DDOS attack-LOIC-UDP')].index)
dt9=d92.groupby('Label').apply(pd.DataFrame.sample, frac=0.3).reset_index(level='Label', drop=True)
print (dt9.value_counts('Label'))
print (d91.value_counts('Label'))

Label
DDOS attack-HOIC    205804
dtype: int64
Label
DDOS attack-LOIC-UDP    1730
dtype: int64


In [60]:
dt9=dt9.groupby('Label').apply(pd.DataFrame.sample, frac=0.6).reset_index(level='Label', drop=True)

In [61]:
print (dt9.value_counts('Label'))

Label
DDOS attack-HOIC    123482
dtype: int64


In [62]:
dt1_1=dt1_1.append ( dt9)
dt1_1=dt1_1.append ( d91)
print (dt1_1.value_counts('Label'))

Label
Benign                      190596
DoS attacks-Hulk            161669
DDOS attack-HOIC            123482
FTP-BruteForce               96680
SSH-Bruteforce               93794
DDoS attacks-LOIC-HTTP       86428
Bot                          71548
DoS attacks-SlowHTTPTest     48962
Infilteration                46532
DoS attacks-GoldenEye        33206
DoS attacks-Slowloris         8792
DDOS attack-LOIC-UDP          1730
dtype: int64


In [63]:
d10=pd.read_csv(r"C:\e\学习资料\02-03\data\Wednesday-28-02-2018_TrafficForML_CICFlowMeter.csv")
print ( d10.value_counts('Label'))

Label
Benign           544200
Infilteration     68871
Label                33
dtype: int64


In [64]:
d10=d10.drop (d10[(d10.Label=='Benign')|(d10.Label=='Label')].index)
d10t=d10.groupby('Label').apply(pd.DataFrame.sample, frac=0.5).reset_index(level='Label', drop=True)
dt1_1=dt1_1.append ( d10t)
print (dt1_1.value_counts('Label'))

Label
Benign                      190596
DoS attacks-Hulk            161669
DDOS attack-HOIC            123482
FTP-BruteForce               96680
SSH-Bruteforce               93794
DDoS attacks-LOIC-HTTP       86428
Infilteration                80968
Bot                          71548
DoS attacks-SlowHTTPTest     48962
DoS attacks-GoldenEye        33206
DoS attacks-Slowloris         8792
DDOS attack-LOIC-UDP          1730
dtype: int64


In [66]:
dt1_1=dt1_1.append (d3_s)
print (dt1_1.value_counts('Label'))

Label
Benign                      190596
DoS attacks-Hulk            161669
DDOS attack-HOIC            123482
FTP-BruteForce               96680
SSH-Bruteforce               93794
DDoS attacks-LOIC-HTTP       86428
Infilteration                80968
Bot                          71548
DoS attacks-SlowHTTPTest     48962
DoS attacks-GoldenEye        33206
DoS attacks-Slowloris         8792
DDOS attack-LOIC-UDP          1730
Brute Force -Web               362
Brute Force -XSS               151
SQL Injection                   53
dtype: int64


In [67]:
dt1_1.to_csv (r"C:\e\学习资料\02-03\data\data_process\integration_a.csv", header=True,index=0 )
print ('done')

done


In [68]:
dataset=pd.read_csv(r"C:\e\学习资料\02-03\data\data_process\integration_a.csv")
print (dataset.value_counts('Label'))

C:\d\anaconda\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning: Columns (80,81,83) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


Label
Benign                      190596
DoS attacks-Hulk            161669
DDOS attack-HOIC            123482
FTP-BruteForce               96680
SSH-Bruteforce               93794
DDoS attacks-LOIC-HTTP       86428
Infilteration                80968
Bot                          71548
DoS attacks-SlowHTTPTest     48962
DoS attacks-GoldenEye        33206
DoS attacks-Slowloris         8792
DDOS attack-LOIC-UDP          1730
Brute Force -Web               362
Brute Force -XSS               151
SQL Injection                   53
dtype: int64


In [70]:
print( dataset.dtypes )


Dst Port           int64
Protocol           int64
Timestamp         object
Flow Duration      int64
Tot Fwd Pkts       int64
                  ...   
Label             object
Flow ID           object
Src IP            object
Src Port         float64
Dst IP            object
Length: 84, dtype: object


In [71]:
dataset.info

<bound method DataFrame.info of         Dst Port  Protocol            Timestamp  Flow Duration  Tot Fwd Pkts  \
0             80         6  02/03/2018 09:17:26            877             3   
1             53        17  02/03/2018 10:34:47           1028             1   
2             80         6  02/03/2018 02:40:09            760             3   
3          49967         6  02/03/2018 10:55:06              0             2   
4           3389         6  02/03/2018 09:16:12        2017512             8   
...          ...       ...                  ...            ...           ...   
998416        80         6  23/02/2018 03:17:24             46             2   
998417        80         6  23/02/2018 10:47:35            277             2   
998418        80         6  23/02/2018 10:22:41            331             2   
998419        80         6  23/02/2018 03:06:20            313             2   
998420        80         6  23/02/2018 10:53:21            190             2   

       

In [72]:
dt1_1.info

<bound method DataFrame.info of        Dst Port Protocol            Timestamp Flow Duration Tot Fwd Pkts  \
908252       80        6  02/03/2018 09:17:26           877            3   
402762       53       17  02/03/2018 10:34:47          1028            1   
706375       80        6  02/03/2018 02:40:09           760            3   
537641    49967        6  02/03/2018 10:55:06             0            2   
961937     3389        6  02/03/2018 09:16:12       2017512            8   
...         ...      ...                  ...           ...          ...   
1588         80        6  23/02/2018 03:17:24            46            2   
1998         80        6  23/02/2018 10:47:35           277            2   
2115         80        6  23/02/2018 10:22:41           331            2   
2216         80        6  23/02/2018 03:06:20           313            2   
2401         80        6  23/02/2018 10:53:21           190            2   

       Tot Bwd Pkts TotLen Fwd Pkts TotLen Bwd Pkts Fwd

In [73]:
dataset['Flow ID'].unique()

array([nan, '172.31.69.25-18.216.200.189-80-58512-6',
       '172.31.69.25-18.216.200.189-80-50107-6', ...,
       '172.31.69.25-18.216.24.42-80-64640-6',
       '172.31.69.25-18.218.115.60-80-56383-6',
       '172.31.69.25-18.218.115.60-80-51651-6'], dtype=object)

In [74]:
dataset['Src IP'].unique()

array([nan, '18.216.200.189', '18.219.9.1', '18.218.115.60',
       '18.219.5.43', '18.216.24.42', '52.14.136.135', '18.218.11.51',
       '18.219.32.43', '18.218.55.126', '18.218.229.235'], dtype=object)

In [75]:
dt1_1['Flow ID'].unique()

array([nan, '172.31.69.25-18.216.200.189-80-58512-6',
       '172.31.69.25-18.216.200.189-80-50107-6', ...,
       '172.31.69.25-18.216.24.42-80-64640-6',
       '172.31.69.25-18.218.115.60-80-56383-6',
       '172.31.69.25-18.218.115.60-80-51651-6'], dtype=object)

In [76]:
dt1_1['Src IP'].unique()

array([nan, '18.216.200.189', '18.219.9.1', '18.218.115.60',
       '18.219.5.43', '18.216.24.42', '52.14.136.135', '18.218.11.51',
       '18.219.32.43', '18.218.55.126', '18.218.229.235'], dtype=object)

In [77]:
#Src Port
dataset['Src Port'].unique()

array([   nan, 58512., 50107., ..., 64876., 50001., 64859.])