In [12]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.metrics import classification_report
from sklearn.svm import OneClassSVM
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

dataset=pd.read_csv(r"C:\e\学习资料\02-03\data\data_process\sp1\d3\split1_d1.csv")
print (dataset.value_counts('Label'))

Label
Benign                      8577
DoS attacks-Hulk            7275
DDOS attack-HOIC            5557
FTP-BruteForce              4351
SSH-Bruteforce              4221
DDoS attacks-LOIC-HTTP      3889
Infilteration               3644
Bot                         3220
DoS attacks-SlowHTTPTest    2203
DoS attacks-GoldenEye       1494
DoS attacks-Slowloris        396
DDOS attack-LOIC-UDP          78
Brute Force -Web              16
Brute Force -XSS               7
SQL Injection                  2
dtype: int64


In [13]:
print ( dataset.shape)

(44930, 78)


In [14]:
dt=pd.read_csv(r"C:\e\学习资料\02-03\data\data_process\sp1\d3\split1_d1_bert.csv",header=None)

print ( dt.shape)


(44930, 768)


In [8]:
dt1=dt.iloc[1:40935,0:768]
print  (dt1.shape)

(40934, 768)


In [9]:
dt1.to_csv(r"C:\e\学习资料\02-03\data\data_process\sp1\d3\split1_d2_bert2.csv",header=None,index=0,mode='a')

In [15]:
labelt=dataset.Label.copy()
print ( labelt.value_counts())
arrs=labelt.values
d1=np.array(arrs)
values = array(d1)
print(values)
# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
data3 = pd.DataFrame(integer_encoded) # header:原第一行的索引，index:原第一列的索引
#data3.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\ptrain1\ptrain2_sli2_labeln.csv",header=None,index=0)
# # binary encode
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)
data4 = pd.DataFrame(onehot_encoded) # header:原第一行的索引，index:原第一列的索引
data4.to_csv(r"C:\e\学习资料\02-03\data\data_process\sp1\d3\split1_d1_bert_label.csv",header=None,index=0)

Benign                      8577
DoS attacks-Hulk            7275
DDOS attack-HOIC            5557
FTP-BruteForce              4351
SSH-Bruteforce              4221
DDoS attacks-LOIC-HTTP      3889
Infilteration               3644
Bot                         3220
DoS attacks-SlowHTTPTest    2203
DoS attacks-GoldenEye       1494
DoS attacks-Slowloris        396
DDOS attack-LOIC-UDP          78
Brute Force -Web              16
Brute Force -XSS               7
SQL Injection                  2
Name: Label, dtype: int64
['Benign' 'Benign' 'Benign' ... 'SSH-Bruteforce' 'SSH-Bruteforce'
 'SSH-Bruteforce']
[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]


In [16]:
print (data4.shape)

(44930, 15)


In [32]:
p1=pd.read_csv(r"C:\e\学习资料\02-03\ptest1\ptest_1.csv")


In [33]:
#print ( p1.value_counts ('Label'))
print ( p1.shape)

(384776, 77)


In [34]:
y1=pd.read_csv(r"C:\e\学习资料\02-03\ptest1\tset_label.csv")
print (y1.shape)

(384776, 14)


In [35]:
y2=pd.read_csv(r"C:\e\学习资料\02-03\ptest1\test_label1.csv")
print ( y2.shape)

(384776, 1)


In [36]:
print ( y2.value_counts())

0 
0     322328
4      18648
7      16566
1       9241
11      8608
13      5944
6       2615
9        649
5        109
2         39
3         14
10         6
12         5
8          4
dtype: int64


In [37]:
pn1 = pd.concat ( [p1,y2],axis=1)
print ( pn1.shape)
print ( pn1.value_counts('Label'))

(384776, 78)


KeyError: 'Label'

In [44]:
p1=pd.read_csv(r"C:\e\学习资料\02-03\data\data_process\split1.csv")

In [40]:
print ( p1.shape)

(249603, 78)


In [46]:
p1.drop_duplicates( keep='first',inplace=True)

In [47]:
print ( p1.shape)

(228103, 78)


In [49]:
p1.value_counts('Label')

Label
Benign                      47633
DoS attacks-Hulk            40209
DDOS attack-HOIC            30831
DDoS attacks-LOIC-HTTP      21607
SSH-Bruteforce              20111
Infilteration               18174
Bot                         17871
FTP-BruteForce              13988
DoS attacks-GoldenEye        8299
DoS attacks-SlowHTTPTest     6684
DoS attacks-Slowloris        2123
DDOS attack-LOIC-UDP          432
Brute Force -Web               90
Brute Force -XSS               38
SQL Injection                  13
dtype: int64

In [50]:
print ( p1.shape )

for index in p1.columns:
    p1[index]=p1[index].fillna(0)
    p1[index]=p1[index].replace(np.Infinity,1)

#X.drop ( columus=[77],axis=1,inplace=True)
#X.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\pva1\pva_1.csv", header=None,index=0)
print (p1.shape)

(228103, 78)
(228103, 78)


In [51]:
p1.to_csv(r"C:\e\学习资料\02-03\data\data_process\split1new.csv",header=True,index=0)

In [52]:
X=pd.read_csv (r"C:\e\学习资料\02-03\data\data_process\split1new.csv")

In [53]:
X.value_counts('Label')

Label
Benign                      47633
DoS attacks-Hulk            40209
DDOS attack-HOIC            30831
DDoS attacks-LOIC-HTTP      21607
SSH-Bruteforce              20111
Infilteration               18174
Bot                         17871
FTP-BruteForce              13988
DoS attacks-GoldenEye        8299
DoS attacks-SlowHTTPTest     6684
DoS attacks-Slowloris        2123
DDOS attack-LOIC-UDP          432
Brute Force -Web               90
Brute Force -XSS               38
SQL Injection                  13
dtype: int64

In [54]:
labelt=X.Label.copy()
print ( labelt.value_counts())
arrs=labelt.values
d1=np.array(arrs)
values = array(d1)
print(values)
# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
data3 = pd.DataFrame(integer_encoded) # header:原第一行的索引，index:原第一列的索引
#data3.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\ptrain1\ptrain2_sli2_labeln.csv",header=None,index=0)
# # binary encode
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)
data4 = pd.DataFrame(onehot_encoded) # header:原第一行的索引，index:原第一列的索引
data4.to_csv(r"C:\e\学习资料\02-03\data\data_process\split1new_y.csv",header=None,index=0)

Benign                      47633
DoS attacks-Hulk            40209
DDOS attack-HOIC            30831
DDoS attacks-LOIC-HTTP      21607
SSH-Bruteforce              20111
Infilteration               18174
Bot                         17871
FTP-BruteForce              13988
DoS attacks-GoldenEye        8299
DoS attacks-SlowHTTPTest     6684
DoS attacks-Slowloris        2123
DDOS attack-LOIC-UDP          432
Brute Force -Web               90
Brute Force -XSS               38
SQL Injection                  13
Name: Label, dtype: int64
['Benign' 'Benign' 'Benign' ... 'SSH-Bruteforce' 'SSH-Bruteforce'
 'SSH-Bruteforce']
[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]


In [55]:
print (data4.shape)

(228103, 15)


In [56]:
X2=pd.read_csv (r"C:\e\学习资料\02-03\data\data_process\split1new_b.csv",header=None)

X3 = pd.concat ( [X,X2],axis=1)
print ( X3.shape)
print ( X3.value_counts('Label'))

(228103, 846)
Label
Benign                      47633
DoS attacks-Hulk            40209
DDOS attack-HOIC            30831
DDoS attacks-LOIC-HTTP      21607
SSH-Bruteforce              20111
Infilteration               18174
Bot                         17871
FTP-BruteForce              13988
DoS attacks-GoldenEye        8299
DoS attacks-SlowHTTPTest     6684
DoS attacks-Slowloris        2123
DDOS attack-LOIC-UDP          432
Brute Force -Web               90
Brute Force -XSS               38
SQL Injection                  13
dtype: int64


In [57]:

X3_1=X3.drop (X3[(X3.Label=='SQL Injection')|(X3.Label=='Brute Force -XSS')|(X3.Label=='Brute Force -Web')|(X3.Label=='DDOS attack-LOIC-UDP')|(X3.Label=='DoS attacks-Slowloris' )].index)
X3_2= X3.drop (X3_1.index)
X3_1.value_counts('Label')

Label
Benign                      47633
DoS attacks-Hulk            40209
DDOS attack-HOIC            30831
DDoS attacks-LOIC-HTTP      21607
SSH-Bruteforce              20111
Infilteration               18174
Bot                         17871
FTP-BruteForce              13988
DoS attacks-GoldenEye        8299
DoS attacks-SlowHTTPTest     6684
dtype: int64

In [66]:
sp1 = X3_1.iloc[:,78:846]
print ( sp1.shape)

(225407, 768)


In [67]:
sp2 = X3_1.iloc[:,0:78]
print ( sp2.shape)

(225407, 78)


In [68]:
sp1.to_csv(r"C:\e\学习资料\02-03\data\data_process\split1new_s1b.csv",header=None,index=0)
sp2.to_csv(r"C:\e\学习资料\02-03\data\data_process\split1new_s1.csv",header=True,index=0)

In [69]:
sp1 = X3_2.iloc[:,78:846]
print ( sp1.shape)
sp2 = X3_2.iloc[:,0:78]
print ( sp2.shape)
sp1.to_csv(r"C:\e\学习资料\02-03\data\data_process\split1new_s2b.csv",header=None,index=0)
sp2.to_csv(r"C:\e\学习资料\02-03\data\data_process\split1new_s2.csv",header=True,index=0)

(2696, 768)
(2696, 78)


In [70]:
labelt=X3_1.Label.copy()
print ( labelt.value_counts())
arrs=labelt.values
d1=np.array(arrs)
values = array(d1)
print(values)
# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
data3 = pd.DataFrame(integer_encoded) # header:原第一行的索引，index:原第一列的索引
#data3.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\ptrain1\ptrain2_sli2_labeln.csv",header=None,index=0)
# # binary encode
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)
data4 = pd.DataFrame(onehot_encoded) # header:原第一行的索引，index:原第一列的索引
data4.to_csv(r"C:\e\学习资料\02-03\data\data_process\split1new_s1y.csv",header=None,index=0)

Benign                      47633
DoS attacks-Hulk            40209
DDOS attack-HOIC            30831
DDoS attacks-LOIC-HTTP      21607
SSH-Bruteforce              20111
Infilteration               18174
Bot                         17871
FTP-BruteForce              13988
DoS attacks-GoldenEye        8299
DoS attacks-SlowHTTPTest     6684
Name: Label, dtype: int64
['Benign' 'Benign' 'Benign' ... 'SSH-Bruteforce' 'SSH-Bruteforce'
 'SSH-Bruteforce']
[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]


In [71]:
X3_11=X3_1.drop (X3_1[(X3_1.Label=='Benign')].index)
X3_12= X3_1.drop (X3_1.index)
X3_11.value_counts('Label')

Label
DoS attacks-Hulk            40209
DDOS attack-HOIC            30831
DDoS attacks-LOIC-HTTP      21607
SSH-Bruteforce              20111
Infilteration               18174
Bot                         17871
FTP-BruteForce              13988
DoS attacks-GoldenEye        8299
DoS attacks-SlowHTTPTest     6684
dtype: int64

In [72]:
sp1 = X3_11.iloc[:,78:846]
print ( sp1.shape)
sp2 = X3_11.iloc[:,0:78]
print ( sp2.shape)
sp1.to_csv(r"C:\e\学习资料\02-03\data\data_process\split1new_s3b.csv",header=None,index=0)
sp2.to_csv(r"C:\e\学习资料\02-03\data\data_process\split1new_s3.csv",header=True,index=0)

(177774, 768)
(177774, 78)


In [73]:
labelt=X3_11.Label.copy()
print ( labelt.value_counts())
arrs=labelt.values
d1=np.array(arrs)
values = array(d1)
print(values)
# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
data3 = pd.DataFrame(integer_encoded) # header:原第一行的索引，index:原第一列的索引
#data3.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\ptrain1\ptrain2_sli2_labeln.csv",header=None,index=0)
# # binary encode
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)
data4 = pd.DataFrame(onehot_encoded) # header:原第一行的索引，index:原第一列的索引
data4.to_csv(r"C:\e\学习资料\02-03\data\data_process\split1new_s3y.csv",header=None,index=0)

DoS attacks-Hulk            40209
DDOS attack-HOIC            30831
DDoS attacks-LOIC-HTTP      21607
SSH-Bruteforce              20111
Infilteration               18174
Bot                         17871
FTP-BruteForce              13988
DoS attacks-GoldenEye        8299
DoS attacks-SlowHTTPTest     6684
Name: Label, dtype: int64
['Bot' 'Bot' 'Bot' ... 'SSH-Bruteforce' 'SSH-Bruteforce' 'SSH-Bruteforce']
[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]
