In [4]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.metrics import classification_report
from sklearn.svm import OneClassSVM
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

d1=pd.read_csv(r"E:\学习心得\data\cic-ids2018\Friday-02-03-2018_TrafficForML_CICFlowMeter.csv")
t1 = d1.groupby('Label').apply(pd.DataFrame.sample, frac=0.3).reset_index(level='Label', drop=True)
print ( t1.shape )
print ( t1['Label'].value_counts())
t1.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\t1.csv",header=1,index=0)

(314572, 80)
Benign    228715
Bot        85857
Name: Label, dtype: int64


In [6]:
t1_1=pd.read_csv(r"E:\学习心得\data\cic-ids2018\02-03\t1.csv")
pt1=t1_1.groupby('Label').apply(pd.DataFrame.sample, frac=0.3).reset_index(level='Label', drop=True)
pt2=t1_1.drop(pt1.index)
print ( pt1.shape )
print ( pt1['Label'].value_counts())
#print ( pt2.shape )
#print ( pt2['Label'].value_counts())
#pt1.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\pt1.csv",header=1,index=0)
pt3=pt2.groupby('Label').apply(pd.DataFrame.sample, frac=0.3).reset_index(level='Label', drop=True)
ptr=pt2.drop ( pt3.index)
print ( pt3.shape )
print ( pt3['Label'].value_counts())
print ( ptr.shape )
print ( ptr['Label'].value_counts())

(94371, 80)
Benign    68614
Bot       25757
Name: Label, dtype: int64
(66060, 80)
Benign    48030
Bot       18030
Name: Label, dtype: int64
(154141, 80)
Benign    112071
Bot        42070
Name: Label, dtype: int64


In [7]:
pt1.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\pva1.csv",header=1,index=0)
pt3.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\ptest1.csv",header=1,index=0)
ptr.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\ptrain1.csv",header=1,index=0)

In [8]:
d1=pd.read_csv(r"E:\学习心得\data\cic-ids2018\Friday-16-02-2018_TrafficForML_CICFlowMeter.csv")
t1 = d1.groupby('Label').apply(pd.DataFrame.sample, frac=0.3).reset_index(level='Label', drop=True)
print ( t1.shape )
print ( t1['Label'].value_counts())
#t1.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\t1.csv",header=1,index=0)
t1_1=t1
pt1=t1_1.groupby('Label').apply(pd.DataFrame.sample, frac=0.3).reset_index(level='Label', drop=True)
pt2=t1_1.drop(pt1.index)
print ( pt1.shape )
print ( pt1['Label'].value_counts())
#print ( pt2.shape )
#print ( pt2['Label'].value_counts())
#pt1.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\pt1.csv",header=1,index=0)
pt3=pt2.groupby('Label').apply(pd.DataFrame.sample, frac=0.3).reset_index(level='Label', drop=True)
ptr=pt2.drop ( pt3.index)
print ( pt3.shape )
print ( pt3['Label'].value_counts())
print ( ptr.shape )
print ( ptr['Label'].value_counts())

D:\ana\envs\tensorflowb\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning: Columns (0,1,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


(314573, 80)
DoS attacks-Hulk            138574
Benign                      134032
DoS attacks-SlowHTTPTest     41967
Name: Label, dtype: int64
(94372, 80)
DoS attacks-Hulk            41572
Benign                      40210
DoS attacks-SlowHTTPTest    12590
Name: Label, dtype: int64
(66061, 80)
DoS attacks-Hulk            29101
Benign                      28147
DoS attacks-SlowHTTPTest     8813
Name: Label, dtype: int64
(154140, 80)
DoS attacks-Hulk            67901
Benign                      65675
DoS attacks-SlowHTTPTest    20564
Name: Label, dtype: int64


In [9]:
pt1.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\pva1.csv",header=False,mode='a',index=0)
pt3.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\ptest1.csv",header=False,mode='a',index=0)
ptr.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\ptrain1.csv",header=False,mode='a',index=0)

In [10]:
d1=pd.read_csv(r"E:\学习心得\data\cic-ids2018\Friday-23-02-2018_TrafficForML_CICFlowMeter.csv")
t1 = d1.groupby('Label').apply(pd.DataFrame.sample, frac=0.3).reset_index(level='Label', drop=True)
print ( t1.shape )
print ( t1['Label'].value_counts())
#t1.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\t1.csv",header=1,index=0)
t1_1=t1
pt1=t1_1.groupby('Label').apply(pd.DataFrame.sample, frac=0.3).reset_index(level='Label', drop=True)
pt2=t1_1.drop(pt1.index)
print ( pt1.shape )
print ( pt1['Label'].value_counts())
#print ( pt2.shape )
#print ( pt2['Label'].value_counts())
#pt1.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\pt1.csv",header=1,index=0)
pt3=pt2.groupby('Label').apply(pd.DataFrame.sample, frac=0.3).reset_index(level='Label', drop=True)
ptr=pt2.drop ( pt3.index)
print ( pt3.shape )
print ( pt3['Label'].value_counts())
print ( ptr.shape )
print ( ptr['Label'].value_counts())

(314573, 80)
Benign              314403
Brute Force -Web       109
Brute Force -XSS        45
SQL Injection           16
Name: Label, dtype: int64
(94373, 80)
Benign              94321
Brute Force -Web       33
Brute Force -XSS       14
SQL Injection           5
Name: Label, dtype: int64
(66060, 80)
Benign              66025
Brute Force -Web       23
Brute Force -XSS        9
SQL Injection           3
Name: Label, dtype: int64
(154140, 80)
Benign              154057
Brute Force -Web        53
Brute Force -XSS        22
SQL Injection            8
Name: Label, dtype: int64


In [11]:
pt1.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\pva1.csv",header=False,mode='a',index=0)
pt3.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\ptest1.csv",header=False,mode='a',index=0)
ptr.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\ptrain1.csv",header=False,mode='a',index=0)

In [13]:
d1=pd.read_csv(r"E:\学习心得\data\cic-ids2018\Thuesday-20-02-2018_TrafficForML_CICFlowMeter.csv")
t1 = d1.groupby('Label').apply(pd.DataFrame.sample, frac=0.03).reset_index(level='Label', drop=True)
print ( t1.shape )
print ( t1['Label'].value_counts())
#t1.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\t1.csv",header=1,index=0)
t1_1=t1
pt1=t1_1.groupby('Label').apply(pd.DataFrame.sample, frac=0.3).reset_index(level='Label', drop=True)
pt2=t1_1.drop(pt1.index)
print ( pt1.shape )
print ( pt1['Label'].value_counts())
#print ( pt2.shape )
#print ( pt2['Label'].value_counts())
#pt1.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\pt1.csv",header=1,index=0)
pt3=pt2.groupby('Label').apply(pd.DataFrame.sample, frac=0.3).reset_index(level='Label', drop=True)
ptr=pt2.drop ( pt3.index)
print ( pt3.shape )
print ( pt3['Label'].value_counts())
print ( ptr.shape )
print ( ptr['Label'].value_counts())

MemoryError: Unable to allocate 2.67 GiB for an array with shape (45, 7948748) and data type float64

In [17]:
d1=pd.read_csv(r"E:\学习心得\data\cic-ids2018\Thursday-01-03-2018_TrafficForML_CICFlowMeter.csv")
t1 = d1.groupby('Label').apply(pd.DataFrame.sample, frac=0.3).reset_index(level='Label', drop=True)

print ( t1.shape )
print ( t1['Label'].value_counts())
#t1.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\t1.csv",header=1,index=0)
t1_1=t1
pt1=t1_1.groupby('Label').apply(pd.DataFrame.sample, frac=0.3).reset_index(level='Label', drop=True)
pt2=t1_1.drop(pt1.index)
print ( pt1.shape )
print ( pt1['Label'].value_counts())
#print ( pt2.shape )
#print ( pt2['Label'].value_counts())
#pt1.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\pt1.csv",header=1,index=0)
pt3=pt2.groupby('Label').apply(pd.DataFrame.sample, frac=0.3).reset_index(level='Label', drop=True)
ptr=pt2.drop ( pt3.index)
print ( pt3.shape )
print ( pt3['Label'].value_counts())
print ( ptr.shape )
print ( ptr['Label'].value_counts())

(99338, 80)
Benign           71411
Infilteration    27919
Label                8
Name: Label, dtype: int64
(29801, 80)
Benign           21423
Infilteration     8376
Label                2
Name: Label, dtype: int64
(20861, 80)
Benign           14996
Infilteration     5863
Label                2
Name: Label, dtype: int64
(48676, 80)
Benign           34992
Infilteration    13680
Label                4
Name: Label, dtype: int64


In [18]:
pt1.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\pva1.csv",header=False,mode='a',index=0)
pt3.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\ptest1.csv",header=False,mode='a',index=0)
ptr.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\ptrain1.csv",header=False,mode='a',index=0)
print ( "done")

done


In [20]:
d1=pd.read_csv(r"E:\学习心得\data\cic-ids2018\Thursday-15-02-2018_TrafficForML_CICFlowMeter.csv")
t1 = d1.groupby('Label').apply(pd.DataFrame.sample, frac=0.3).reset_index(level='Label', drop=True)
print ( t1.shape )
print ( t1['Label'].value_counts())
#t1.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\t1.csv",header=1,index=0)
t1_1=t1
pt1=t1_1.groupby('Label').apply(pd.DataFrame.sample, frac=0.3).reset_index(level='Label', drop=True)
pt2=t1_1.drop(pt1.index)
print ( pt1.shape )
print ( pt1['Label'].value_counts())
#print ( pt2.shape )
#print ( pt2['Label'].value_counts())
#pt1.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\pt1.csv",header=1,index=0)
pt3=pt2.groupby('Label').apply(pd.DataFrame.sample, frac=0.3).reset_index(level='Label', drop=True)
ptr=pt2.drop ( pt3.index)
print ( pt3.shape )
print ( pt3['Label'].value_counts())
print ( ptr.shape )
print ( ptr['Label'].value_counts())

(314572, 80)
Benign                   298823
DoS attacks-GoldenEye     12452
DoS attacks-Slowloris      3297
Name: Label, dtype: int64
(94372, 80)
Benign                   89647
DoS attacks-GoldenEye     3736
DoS attacks-Slowloris      989
Name: Label, dtype: int64
(66060, 80)
Benign                   62753
DoS attacks-GoldenEye     2615
DoS attacks-Slowloris      692
Name: Label, dtype: int64
(154140, 80)
Benign                   146423
DoS attacks-GoldenEye      6101
DoS attacks-Slowloris      1616
Name: Label, dtype: int64


In [21]:
pt1.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\pva1.csv",header=False,mode='a',index=0)
pt3.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\ptest1.csv",header=False,mode='a',index=0)
ptr.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\ptrain1.csv",header=False,mode='a',index=0)
print ( "done")

done


In [22]:
d1=pd.read_csv(r"E:\学习心得\data\cic-ids2018\Thursday-22-02-2018_TrafficForML_CICFlowMeter.csv")
t1 = d1.groupby('Label').apply(pd.DataFrame.sample, frac=0.3).reset_index(level='Label', drop=True)
print ( t1.shape )
print ( t1['Label'].value_counts())
#t1.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\t1.csv",header=1,index=0)
t1_1=t1
pt1=t1_1.groupby('Label').apply(pd.DataFrame.sample, frac=0.3).reset_index(level='Label', drop=True)
pt2=t1_1.drop(pt1.index)
print ( pt1.shape )
print ( pt1['Label'].value_counts())
#print ( pt2.shape )
#print ( pt2['Label'].value_counts())
#pt1.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\pt1.csv",header=1,index=0)
pt3=pt2.groupby('Label').apply(pd.DataFrame.sample, frac=0.3).reset_index(level='Label', drop=True)
ptr=pt2.drop ( pt3.index)
print ( pt3.shape )
print ( pt3['Label'].value_counts())
print ( ptr.shape )
print ( ptr['Label'].value_counts())

(314573, 80)
Benign              314464
Brute Force -Web        75
Brute Force -XSS        24
SQL Injection           10
Name: Label, dtype: int64
(94371, 80)
Benign              94339
Brute Force -Web       22
Brute Force -XSS        7
SQL Injection           3
Name: Label, dtype: int64
(66061, 80)
Benign              66038
Brute Force -Web       16
Brute Force -XSS        5
SQL Injection           2
Name: Label, dtype: int64
(154141, 80)
Benign              154087
Brute Force -Web        37
Brute Force -XSS        12
SQL Injection            5
Name: Label, dtype: int64


In [23]:
pt1.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\pva1.csv",header=False,mode='a',index=0)
pt3.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\ptest1.csv",header=False,mode='a',index=0)
ptr.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\ptrain1.csv",header=False,mode='a',index=0)
print ( "done")

done


In [24]:
d1=pd.read_csv(r"E:\学习心得\data\cic-ids2018\Wednesday-14-02-2018_TrafficForML_CICFlowMeter.csv")
t1 = d1.groupby('Label').apply(pd.DataFrame.sample, frac=0.3).reset_index(level='Label', drop=True)
print ( t1.shape )
print ( t1['Label'].value_counts())
#t1.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\t1.csv",header=1,index=0)
t1_1=t1
pt1=t1_1.groupby('Label').apply(pd.DataFrame.sample, frac=0.3).reset_index(level='Label', drop=True)
pt2=t1_1.drop(pt1.index)
print ( pt1.shape )
print ( pt1['Label'].value_counts())
#print ( pt2.shape )
#print ( pt2['Label'].value_counts())
#pt1.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\pt1.csv",header=1,index=0)
pt3=pt2.groupby('Label').apply(pd.DataFrame.sample, frac=0.3).reset_index(level='Label', drop=True)
ptr=pt2.drop ( pt3.index)
print ( pt3.shape )
print ( pt3['Label'].value_counts())
print ( ptr.shape )
print ( ptr['Label'].value_counts())

(314573, 80)
Benign            200288
FTP-BruteForce     58008
SSH-Bruteforce     56277
Name: Label, dtype: int64
(94371, 80)
Benign            60086
FTP-BruteForce    17402
SSH-Bruteforce    16883
Name: Label, dtype: int64
(66061, 80)
Benign            42061
FTP-BruteForce    12182
SSH-Bruteforce    11818
Name: Label, dtype: int64
(154141, 80)
Benign            98141
FTP-BruteForce    28424
SSH-Bruteforce    27576
Name: Label, dtype: int64


In [25]:
pt1.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\pva1.csv",header=False,mode='a',index=0)
pt3.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\ptest1.csv",header=False,mode='a',index=0)
ptr.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\ptrain1.csv",header=False,mode='a',index=0)
print ( "done")

done


In [26]:
d1=pd.read_csv(r"E:\学习心得\data\cic-ids2018\Wednesday-21-02-2018_TrafficForML_CICFlowMeter.csv")
t1 = d1.groupby('Label').apply(pd.DataFrame.sample, frac=0.3).reset_index(level='Label', drop=True)
print ( t1.shape )
print ( t1['Label'].value_counts())
#t1.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\t1.csv",header=1,index=0)
t1_1=t1
pt1=t1_1.groupby('Label').apply(pd.DataFrame.sample, frac=0.3).reset_index(level='Label', drop=True)
pt2=t1_1.drop(pt1.index)
print ( pt1.shape )
print ( pt1['Label'].value_counts())
#print ( pt2.shape )
#print ( pt2['Label'].value_counts())
#pt1.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\pt1.csv",header=1,index=0)
pt3=pt2.groupby('Label').apply(pd.DataFrame.sample, frac=0.3).reset_index(level='Label', drop=True)
ptr=pt2.drop ( pt3.index)
print ( pt3.shape )
print ( pt3['Label'].value_counts())
print ( ptr.shape )
print ( ptr['Label'].value_counts())

(314573, 80)
DDOS attack-HOIC        205804
Benign                  108250
DDOS attack-LOIC-UDP       519
Name: Label, dtype: int64
(94372, 80)
DDOS attack-HOIC        61741
Benign                  32475
DDOS attack-LOIC-UDP      156
Name: Label, dtype: int64
(66060, 80)
DDOS attack-HOIC        43219
Benign                  22732
DDOS attack-LOIC-UDP      109
Name: Label, dtype: int64
(154141, 80)
DDOS attack-HOIC        100844
Benign                   53043
DDOS attack-LOIC-UDP       254
Name: Label, dtype: int64


In [27]:
pt1.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\pva1.csv",header=False,mode='a',index=0)
pt3.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\ptest1.csv",header=False,mode='a',index=0)
ptr.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\ptrain1.csv",header=False,mode='a',index=0)
print ( "done")

done


In [28]:
d1=pd.read_csv(r"E:\学习心得\data\cic-ids2018\Wednesday-28-02-2018_TrafficForML_CICFlowMeter.csv")
t1 = d1.groupby('Label').apply(pd.DataFrame.sample, frac=0.3).reset_index(level='Label', drop=True)
print ( t1.shape )
print ( t1['Label'].value_counts())
#t1.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\t1.csv",header=1,index=0)
t1_1=t1
pt1=t1_1.groupby('Label').apply(pd.DataFrame.sample, frac=0.3).reset_index(level='Label', drop=True)
pt2=t1_1.drop(pt1.index)
print ( pt1.shape )
print ( pt1['Label'].value_counts())
#print ( pt2.shape )
#print ( pt2['Label'].value_counts())
#pt1.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\pt1.csv",header=1,index=0)
pt3=pt2.groupby('Label').apply(pd.DataFrame.sample, frac=0.3).reset_index(level='Label', drop=True)
ptr=pt2.drop ( pt3.index)
print ( pt3.shape )
print ( pt3['Label'].value_counts())
print ( ptr.shape )
print ( ptr['Label'].value_counts())

(183931, 80)
Benign           163260
Infilteration     20661
Label                10
Name: Label, dtype: int64
(55179, 80)
Benign           48978
Infilteration     6198
Label                3
Name: Label, dtype: int64
(38626, 80)
Benign           34285
Infilteration     4339
Label                2
Name: Label, dtype: int64
(90126, 80)
Benign           79997
Infilteration    10124
Label                5
Name: Label, dtype: int64


In [29]:
pt1.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\pva1.csv",header=False,mode='a',index=0)
pt3.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\ptest1.csv",header=False,mode='a',index=0)
ptr.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\ptrain1.csv",header=False,mode='a',index=0)
print ( "done")

done


In [30]:
df=pd.read_csv(r"E:\学习心得\data\cic-ids2018\02-03\ptrain1.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1222654 entries, 0 to 1222653
Data columns (total 80 columns):
 #   Column             Non-Null Count    Dtype 
---  ------             --------------    ----- 
 0   Dst Port           1222654 non-null  object
 1   Protocol           1222654 non-null  object
 2   Timestamp          1222654 non-null  object
 3   Flow Duration      1222654 non-null  object
 4   Tot Fwd Pkts       1222654 non-null  object
 5   Tot Bwd Pkts       1222654 non-null  object
 6   TotLen Fwd Pkts    1222654 non-null  object
 7   TotLen Bwd Pkts    1222654 non-null  object
 8   Fwd Pkt Len Max    1222654 non-null  object
 9   Fwd Pkt Len Min    1222654 non-null  object
 10  Fwd Pkt Len Mean   1222654 non-null  object
 11  Fwd Pkt Len Std    1222654 non-null  object
 12  Bwd Pkt Len Max    1222654 non-null  object
 13  Bwd Pkt Len Min    1222654 non-null  object
 14  Bwd Pkt Len Mean   1222654 non-null  object
 15  Bwd Pkt Len Std    1222654 non-null  object
 16  

In [31]:
df['Label'].unique()

array(['Benign', 'Bot', 'DoS attacks-Hulk', 'DoS attacks-SlowHTTPTest',
       'Brute Force -Web', 'Brute Force -XSS', 'SQL Injection',
       'Infilteration', 'Label', 'DoS attacks-GoldenEye',
       'DoS attacks-Slowloris', 'FTP-BruteForce', 'SSH-Bruteforce',
       'DDOS attack-HOIC', 'DDOS attack-LOIC-UDP'], dtype=object)

In [32]:
 pd.Categorical(df['Flow Pkts/s'])# to check different value

[8284.023669, 10101.0101, 9.078348, 5.184172, 0.502296, ..., 'Flow Pkts/s', 'Flow Pkts/s', 'Flow Pkts/s', 'Flow Pkts/s', 'Flow Pkts/s']
Length: 1222654
Categories (576386, object): [-0.000061, 0.016668, 0.016669, 0.01667, ..., '999.5002499', 'Flow Pkts/s', 'Infinity', 'inf']

In [33]:
df['Flow Pkts/s'].unique()

array([8284.023669, 10101.0101, 9.078347959, ..., '9.144863787',
       '15.86147045', '42.50029219'], dtype=object)

In [34]:
df.drop('Timestamp',axis=1,inplace=True)

In [35]:
df.shape

(1222654, 79)

In [36]:
df.drop('Protocol',axis=1,inplace=True)
df.drop('Dst Port',axis=1,inplace=True)
df.shape

(1222654, 77)

In [37]:
df['Flow Pkts/s']= df['Flow Pkts/s'].fillna(0)  # removing NAN and INF values
df['Flow Byts/s']= df['Flow Byts/s'].fillna(0)
df['Flow Pkts/s']= df['Flow Pkts/s'].replace(np.Infinity,1)
df['Flow Byts/s']= df['Flow Byts/s'].replace(np.Infinity,1)

In [38]:
pd.Categorical(df['Flow Byts/s']) # now no INF and NAN values

[462721.8935, 0.0, 1649.233212, 747.227764, 0.0, ..., 'Flow Byts/s', 'Flow Byts/s', 'Flow Byts/s', 'Flow Byts/s', 'Flow Byts/s']
Length: 1222654
Categories (601738, object): [0.0, 0.008362, 0.008437, 0.008451, ..., '9998.324303', 'Flow Byts/s', 'Infinity', 'inf']

In [39]:
 pd.Categorical(df['Flow Pkts/s'])

[8284.023669, 10101.0101, 9.078348, 5.184172, 0.502296, ..., 'Flow Pkts/s', 'Flow Pkts/s', 'Flow Pkts/s', 'Flow Pkts/s', 'Flow Pkts/s']
Length: 1222654
Categories (576386, object): [-0.000061, 0.016668, 0.016669, 0.01667, ..., '999.5002499', 'Flow Pkts/s', 'Infinity', 'inf']

In [40]:
df.shape

(1222654, 77)

In [45]:
labelt = df.Label.copy()
labelt.shape
labelt.unique()
labelt.value_counts()

AttributeError: 'DataFrame' object has no attribute 'Label'

In [42]:
df.drop('Label',axis=1,inplace=True)

In [43]:
df.shape

(1222654, 76)

In [44]:
arrs=labelt.values
d1=np.array(arrs)
values = array(d1)
print(values)
# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
data3 = pd.DataFrame(integer_encoded) # header:原第一行的索引，index:原第一列的索引
#data3.to_csv(r"E:\学习心得\data\cic-ids2018\28-02\28pl1.csv",header=None,index=0)
# # binary encode
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)
data4 = pd.DataFrame(onehot_encoded) # header:原第一行的索引，index:原第一列的索引
data4.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\ptrain1\train_label.csv",header=None,index=0)

['Benign' 'Benign' 'Benign' ... 'Label' 'Label' 'Label']
[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]]


In [59]:
labelt.drop(index=labelt.isin(["Label"]).index,axis=0,inplace=True)
print (labelt.shape)
labelt.unique()
labelt.value_counts()


(0,)


Series([], Name: Label, dtype: int64)

In [48]:
#labelt.drop('Label')
print ( df.shape )
#df.drop("Flow Duration",axis=0,inplace=True)
print ( df.shape )

(1222654, 76)


KeyError: "['Flow Duration'] not found in axis"

In [70]:
df=pd.read_csv(r"E:\学习心得\data\cic-ids2018\02-03\ptrain1.csv")

In [82]:
print ( df.shape)
df1=df
print ( df1.shape )
print  (df.Protocol.isin(['Protocol']).index)
print ( df.duplicated())
#norepeat_df = df.drop_duplicates(subset=['Protocol'], keep='first')
#去掉A_ID和B_ID列中重复的行，并保留重复出现的行中第一次出现的行
#df.drop ( index=df['Timestamp'].isin(["stamp"]).index,axis=0,inplace=True)
print ( df.shape )
#labelt.drop(index=labelt.isin(["Label"]).index,axis=0,inplace=True)
df2=df.drop ( index=[1222649,1222651,1222652,1222653,1222650],axis=0)
#df1.unique()
df2.value_counts("Label")
print ( df2.duplicated())

(1222654, 80)
(1222654, 80)
RangeIndex(start=0, stop=1222654, step=1)
0          False
1          False
2          False
3          False
4          False
           ...  
1222649     True
1222650     True
1222651     True
1222652     True
1222653     True
Length: 1222654, dtype: bool
(1222654, 80)
0          False
1          False
2          False
3          False
4          False
           ...  
1222644    False
1222645    False
1222646    False
1222647    False
1222648    False
Length: 1222649, dtype: bool


In [84]:
print ( df2.duplicated()==True)
df2.value_counts("Label")


0          False
1          False
2          False
3          False
4          False
           ...  
1222644    False
1222645    False
1222646    False
1222647    False
1222648    False
Length: 1222649, dtype: bool


Label
Benign                      901985
DDOS attack-HOIC            100844
DoS attacks-Hulk             67901
Bot                          42070
FTP-BruteForce               28424
SSH-Bruteforce               27576
Infilteration                25172
DoS attacks-SlowHTTPTest     20564
DoS attacks-GoldenEye         6101
DoS attacks-Slowloris         1616
DDOS attack-LOIC-UDP           254
Brute Force -Web                90
Brute Force -XSS                34
SQL Injection                   13
Label                            5
dtype: int64

In [86]:
print ( df2.shape )
df3= df2.drop_duplicates( keep=False)
print ( df3.shape)
df3.value_counts("Label")

(1222649, 80)
(1174778, 80)


Label
Benign                      900405
DDOS attack-HOIC            100090
DoS attacks-Hulk             66484
Bot                          41887
Infilteration                24996
SSH-Bruteforce               20085
FTP-BruteForce                8483
DoS attacks-GoldenEye         6099
DoS attacks-SlowHTTPTest      4311
DoS attacks-Slowloris         1547
DDOS attack-LOIC-UDP           254
Brute Force -Web                90
Brute Force -XSS                34
SQL Injection                   13
dtype: int64

In [87]:
df3['Label'].unique()

array(['Benign', 'Bot', 'DoS attacks-Hulk', 'DoS attacks-SlowHTTPTest',
       'Brute Force -Web', 'Brute Force -XSS', 'SQL Injection',
       'Infilteration', 'DoS attacks-GoldenEye', 'DoS attacks-Slowloris',
       'FTP-BruteForce', 'SSH-Bruteforce', 'DDOS attack-HOIC',
       'DDOS attack-LOIC-UDP'], dtype=object)

In [88]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1174778 entries, 0 to 1222648
Data columns (total 80 columns):
 #   Column             Non-Null Count    Dtype 
---  ------             --------------    ----- 
 0   Dst Port           1174778 non-null  object
 1   Protocol           1174778 non-null  object
 2   Timestamp          1174778 non-null  object
 3   Flow Duration      1174778 non-null  object
 4   Tot Fwd Pkts       1174778 non-null  object
 5   Tot Bwd Pkts       1174778 non-null  object
 6   TotLen Fwd Pkts    1174778 non-null  object
 7   TotLen Bwd Pkts    1174778 non-null  object
 8   Fwd Pkt Len Max    1174778 non-null  object
 9   Fwd Pkt Len Min    1174778 non-null  object
 10  Fwd Pkt Len Mean   1174778 non-null  object
 11  Fwd Pkt Len Std    1174778 non-null  object
 12  Bwd Pkt Len Max    1174778 non-null  object
 13  Bwd Pkt Len Min    1174778 non-null  object
 14  Bwd Pkt Len Mean   1174778 non-null  object
 15  Bwd Pkt Len Std    1174778 non-null  object
 16  

In [89]:
df2.dtypes

Dst Port         object
Protocol         object
Timestamp        object
Flow Duration    object
Tot Fwd Pkts     object
                  ...  
Idle Mean        object
Idle Std         object
Idle Max         object
Idle Min         object
Label            object
Length: 80, dtype: object

In [93]:
df3.value_counts("Label")

Label
Benign                      900405
DDOS attack-HOIC            100090
DoS attacks-Hulk             66484
Bot                          41887
Infilteration                24996
SSH-Bruteforce               20085
FTP-BruteForce                8483
DoS attacks-GoldenEye         6099
DoS attacks-SlowHTTPTest      4311
DoS attacks-Slowloris         1547
DDOS attack-LOIC-UDP           254
Brute Force -Web                90
Brute Force -XSS                34
SQL Injection                   13
dtype: int64

In [95]:
df4=df3.drop('Timestamp',axis=1)

KeyError: "['Timestamp'] not found in axis"

In [96]:
df3['Flow Pkts/s']= df3['Flow Pkts/s'].fillna(0)  # removing NAN and INF values
df3['Flow Byts/s']= df3['Flow Byts/s'].fillna(0)
df3['Flow Pkts/s']= df3['Flow Pkts/s'].replace(np.Infinity,1)
df3['Flow Byts/s']= df3['Flow Byts/s'].replace(np.Infinity,1)

C:\Users\44742\AppData\Local\Temp/ipykernel_9280/4029331248.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3['Flow Pkts/s']= df3['Flow Pkts/s'].fillna(0)  # removing NAN and INF values
C:\Users\44742\AppData\Local\Temp/ipykernel_9280/4029331248.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3['Flow Byts/s']= df3['Flow Byts/s'].fillna(0)
C:\Users\44742\AppData\Local\Temp/ipykernel_9280/4029331248.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
T

In [97]:
df3.shape

(1174778, 79)

In [98]:
df3.drop('Protocol',axis=1,inplace=True)
df3.drop('Dst Port',axis=1,inplace=True)
df3.shape

(1174778, 77)

In [99]:
labelt = df3.Label.copy()
labelt.shape

(1174778,)

In [100]:
print ( labelt.value_counts())
arrs=labelt.values
d1=np.array(arrs)
values = array(d1)
print(values)
# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
data3 = pd.DataFrame(integer_encoded) # header:原第一行的索引，index:原第一列的索引
#data3.to_csv(r"E:\学习心得\data\cic-ids2018\28-02\28pl1.csv",header=None,index=0)
# # binary encode
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)
data4 = pd.DataFrame(onehot_encoded) # header:原第一行的索引，index:原第一列的索引
data4.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\ptrain1\train_label.csv",header=None,index=0)

Benign                      900405
DDOS attack-HOIC            100090
DoS attacks-Hulk             66484
Bot                          41887
Infilteration                24996
SSH-Bruteforce               20085
FTP-BruteForce                8483
DoS attacks-GoldenEye         6099
DoS attacks-SlowHTTPTest      4311
DoS attacks-Slowloris         1547
DDOS attack-LOIC-UDP           254
Brute Force -Web                90
Brute Force -XSS                34
SQL Injection                   13
Name: Label, dtype: int64
['Benign' 'Benign' 'Benign' ... 'Infilteration' 'Infilteration'
 'Infilteration']
[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]]


In [104]:
print ( df3.shape)
#df3.drop('Label',axis=1,inplace=True)
print ( df3.shape)
#print ( df4.shape )

(1174778, 76)
(1174778, 76)


In [102]:
df3.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\ptrain1\ptrain_1.csv",header=None,index=0)

In [105]:
df=pd.read_csv(r"E:\学习心得\data\cic-ids2018\02-03\ptest1.csv")
print ( df.shape)        
df.drop('Protocol',axis=1,inplace=True)
df.drop('Dst Port',axis=1,inplace=True)
df.drop('Timestamp',axis=1,inplace=True)
df['Flow Pkts/s']= df['Flow Pkts/s'].fillna(0)  # removing NAN and INF values
df['Flow Byts/s']= df['Flow Byts/s'].fillna(0)
df['Flow Pkts/s']= df['Flow Pkts/s'].replace(np.Infinity,1)
df['Flow Byts/s']= df['Flow Byts/s'].replace(np.Infinity,1)
print ( df.shape )
df3= df.drop_duplicates( keep=False)
print ( df3.shape )
print ( df3.value_counts("Label"))

D:\ana\envs\tensorflowb\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning: Columns (0,1,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


(523996, 80)
(523996, 77)
(384777, 77)
Label
Benign                      322329
DDOS attack-HOIC             18648
DoS attacks-Hulk             16566
Bot                           9241
Infilteration                 8608
SSH-Bruteforce                5944
DoS attacks-GoldenEye         2615
DoS attacks-Slowloris          649
DDOS attack-LOIC-UDP           109
Brute Force -Web                39
Brute Force -XSS                14
FTP-BruteForce                   6
SQL Injection                    5
DoS attacks-SlowHTTPTest         4
dtype: int64


In [106]:
labelt = df3.Label.copy()
labelt.shape

(384777,)

In [107]:
print ( labelt.value_counts())
arrs=labelt.values
d1=np.array(arrs)
values = array(d1)
print(values)
# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
data3 = pd.DataFrame(integer_encoded) # header:原第一行的索引，index:原第一列的索引
data3.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\ptest1\test_label1.csv",header=None,index=0)
# # binary encode
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)
data4 = pd.DataFrame(onehot_encoded) # header:原第一行的索引，index:原第一列的索引
data4.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\ptest1\tset_label.csv",header=None,index=0)

Benign                      322329
DDOS attack-HOIC             18648
DoS attacks-Hulk             16566
Bot                           9241
Infilteration                 8608
SSH-Bruteforce                5944
DoS attacks-GoldenEye         2615
DoS attacks-Slowloris          649
DDOS attack-LOIC-UDP           109
Brute Force -Web                39
Brute Force -XSS                14
FTP-BruteForce                   6
SQL Injection                    5
DoS attacks-SlowHTTPTest         4
Name: Label, dtype: int64
['Benign' 'Benign' 'Benign' ... 'Infilteration' 'Infilteration'
 'Infilteration']
[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]]


In [108]:
df3.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\ptest1\ptest_1.csv",header=None,index=0)

In [109]:
df=pd.read_csv(r"E:\学习心得\data\cic-ids2018\02-03\pva1.csv")
print ( df.shape)        
df.drop('Protocol',axis=1,inplace=True)
df.drop('Dst Port',axis=1,inplace=True)
df.drop('Timestamp',axis=1,inplace=True)
df['Flow Pkts/s']= df['Flow Pkts/s'].fillna(0)  # removing NAN and INF values
df['Flow Byts/s']= df['Flow Byts/s'].fillna(0)
df['Flow Pkts/s']= df['Flow Pkts/s'].replace(np.Infinity,1)
df['Flow Byts/s']= df['Flow Byts/s'].replace(np.Infinity,1)
print ( df.shape )
df3= df.drop_duplicates( keep=False)
print ( df3.shape )
print ( df3.value_counts("Label"))

D:\ana\envs\tensorflowb\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning: Columns (0,1,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


(748562, 80)
(748562, 77)
(534416, 77)
Label
Benign                      451401
DDOS attack-HOIC             23358
DoS attacks-Hulk             20996
Bot                          13021
Infilteration                12228
SSH-Bruteforce                8514
DoS attacks-GoldenEye         3732
DoS attacks-Slowloris          916
DDOS attack-LOIC-UDP           156
Brute Force -Web                55
Brute Force -XSS                19
DoS attacks-SlowHTTPTest         8
SQL Injection                    8
FTP-BruteForce                   4
dtype: int64


In [110]:
labelt = df3.Label.copy()
labelt.shape

(534416,)

In [111]:
print ( labelt.value_counts())
arrs=labelt.values
d1=np.array(arrs)
values = array(d1)
print(values)
# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
data3 = pd.DataFrame(integer_encoded) # header:原第一行的索引，index:原第一列的索引
data3.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\pva1\pva_label1.csv",header=None,index=0)
# # binary encode
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)
data4 = pd.DataFrame(onehot_encoded) # header:原第一行的索引，index:原第一列的索引
data4.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\pva1\pva_label.csv",header=None,index=0)

Benign                      451401
DDOS attack-HOIC             23358
DoS attacks-Hulk             20996
Bot                          13021
Infilteration                12228
SSH-Bruteforce                8514
DoS attacks-GoldenEye         3732
DoS attacks-Slowloris          916
DDOS attack-LOIC-UDP           156
Brute Force -Web                55
Brute Force -XSS                19
DoS attacks-SlowHTTPTest         8
SQL Injection                    8
FTP-BruteForce                   4
Name: Label, dtype: int64
['Benign' 'Benign' 'Benign' ... 'Infilteration' 'Infilteration'
 'Infilteration']
[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]]


In [112]:
df3.to_csv(r"E:\学习心得\data\cic-ids2018\02-03\pva1\pva_1.csv",header=None,index=0)